### ISSUE TITLE
Selling items via the cargo shuttle is broken

### ISSUE THREAD

**Issue by Glloyd** [UristMcStation/UristMcStation#1068]
#### Description of issue

Selling items via the cargo shuttle does not work. I'm more adding this as a reminder for myself when I have more free time, although if anyone is currently working on anything related to trading this might be something you want to hit along the way.

#### Difference between expected and actual behavior

We don't get money, I expect to get money.

#### Steps to reproduce 

Put an item in a crate, either from the trade_items list or not, and send it on the cargo shuttle. You only get the crate money.

#### Specific information for locating

It's failing in the supply subsystem find_item_value() proc, it probably needs to be rewritten like @CPU-Blanc did for the NPC trading logic.

#### Length of time in which bug has been known to occur

Unknown, but seemingly for a while. It worked when I first added it, but at some point it broke.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by CPU-Blanc** [comment]
I'll likely be putting together another bugfixing pr over the next few days to tackle some other issues. I can take a look at it then if you'd like?

**Comment by Glloyd** [comment]
Sure, if you'd like, but don't feel any pressure if you're busy with other things, I'll get to this eventually.

**Comment by Glloyd** [comment]
@CPU-Blanc I might need to take you up on your offer. I want to get this fixed up sooner rather than later, but I won't have a chance until sometime later in June unfortunately.

**Comment by CPU-Blanc** [comment]
No worries! I should have some time coming up on Monday, so I can take a look at it then as well as some other bug fixes
