### ISSUE TITLE
AOOC Verb Shows Up For Non-Antags

### ISSUE THREAD

**Issue by Glloyd** [UristMcStation/UristMcStation#116]
@TGameCo fix pls

They can't use it, but it's on the ui.

**Comment by scrdest** [comment]
Having messed with adding verbs lately, yeah, the best way would be to remove the verb being usable by everyone and add it in antag setup. Not sure how the merges would look upon this, but if this was ours and ours code alone, that would be the way.

**Comment by CPU-Blanc** [comment]
Old issue. Has since been fixed.
