### ISSUE TITLE
Mime Equipment & Name Issues on Spawn.

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1273]
### Description of issue

When the Mime spawns, they don't get the oppurtunity to change their name, and also update the manifest to the new name change.

Additionally they do not spawn with their backpack, including the mime items. As well as suspenders.

### Difference between expected and actual behaviour

Mime should be able to pick their stage name, like Clowns.
Mimes should spawn with their gear.

### Steps to reproduce

Spawn as Mime.
See your lack of things.

### Specific information for locating

Look into Mime Role Job-Spawning for broken things and adjust.

### Client version, server revision, & game ID

Current Baymerge-Testing.
Worked fine on previous Master Build of Urist.

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Fixed in #1309
