### ISSUE TITLE
Possible Spam Abuse Detected - Baymerge

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1275]
### Description of issue

On the Baymerge Version of our codebase, I'm running into consistent Spam Abuse kicking during the round, usually around 5/15 times every 2 hour shift. Which can be incredibly frustrating, especially when playing as an Antag.

I've tried clearing the cache, returning to Legacy Chat from Goonchat, disabling it via character setup. I also thought it was related to the Clown Noisemaker, but I'm unsure of such. Some rounds I seem to have it less than more, and I'm not sure if it's related to the timer/bucket issue or not. As other people from the UK don't seem to run into this spam ping issue.

### Difference between expected and actual behaviour

Master Build of Urist had no spam-kicking issues and I am able to play without being kicked every 10/15 minutes, or less.

### Steps to reproduce

1. Spawn into a round.
2. Spend around 5-10 minutes walking around.
3. Kicked for Spam Abuse detection.
4. Sometimes going up a Z-Level seems to make it a higher chance (Maybe? It feels like it)

### Specific information for locating

Could be related to specific map problems, i.e timer/bucket, goonchat, noisemaker, something else. I'm not sure anymore and I can't profile a reason as to why either.

### Client version, server revision, & game ID

Current Baymerge Build.
Did not happen before Baymerge

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Has this happened to you while you're not playing clown? Just trying to figure out what might cause it, as it's weird it effects almost selectively you.

**Comment by Yantarii** [comment]
> Has this happened to you while you're not playing clown? Just trying to figure out what might cause it, as it's weird it effects almost selectively you.

Yeah, it happens when I play any other role, Mime, Security, QM, anything

**Comment by Yantarii** [comment]
I've also reinstalled Byond a couple of times too, cleared cache in options as well, not sure what else on my end

**Comment by ggermanicus** [comment]
Happens to @CaraS212, it's happened to ryanwraith as well.

**Comment by Yantarii** [comment]
From yesterday's round, it looks like having high ping (despite having 0.14 ping pong), or when the Garbage Controller is backed up with stuff to do (yesterday had a bunch of angry deletes) contributes heavily towards spam kicks - Moving (by holding the keys) seems to make the server think you are consistently spamming move inputs key and kick you. I managed to somewhat avoid this when it was incredibly laggy by tap moving, or stopping when I felt a large input lag, but this isn't a great stopgap fix either. @CaraS212 ran into similar as well in round.

**Comment by scrdest** [comment]
> From yesterday's round, it looks like having high ping (despite having 0.14 ping pong), or when the Garbage Controller is backed up with stuff to do (yesterday had a bunch of angry deletes) contributes heavily towards spam kicks - Moving (by holding the keys) seems to make the server think you are consistently spamming move inputs key and kick you. I managed to somewhat avoid this when it was incredibly laggy by tap moving, or stopping when I felt a large input lag, but this isn't a great stopgap fix either. @CaraS212 ran into similar as well in round.

That kinda makes sense. Move inputs are instant verbs, which are the main thing that gets checked for spam. 

I don't think anybody not named Lummox knows how BYOND networking really works, but it might be that high-latency connections just wind up hitting the server with all the delayed actions all in one meaty chunk of requests.

This would then trip the alarm because the server would try to process 'em all miliseconds apart. The spam protection checks the server-side time of each request, so this would show up as if someone with a saner ping just tried to DDOS the server.

A possible solution is to throttle the verbs and refuse to execute them rather than kick people. The tricky bit is that would still incur server-side load, so could still have DDOSers. 

I don't think making these verbs noninstant would be viable - instant means you can execute this verb alongside other inputs, so it's smoother... I guess an option would be to create alternate non-instant movement commands and some kind of skin-level toggle to let players with high latency switch to them.

**Comment by Yantarii** [comment]
> > From yesterday's round, it looks like having high ping (despite having 0.14 ping pong), or when the Garbage Controller is backed up with stuff to do (yesterday had a bunch of angry deletes) contributes heavily towards spam kicks - Moving (by holding the keys) seems to make the server think you are consistently spamming move inputs key and kick you. I managed to somewhat avoid this when it was incredibly laggy by tap moving, or stopping when I felt a large input lag, but this isn't a great stopgap fix either. @CaraS212 ran into similar as well in round.
> 
> That kinda makes sense. Move inputs are instant verbs, which are the main thing that gets checked for spam.
> 
> I don't think anybody not named Lummox knows how BYOND networking really works, but it might be that high-latency connections just wind up hitting the server with all the delayed actions all in one meaty chunk of requests.
> 
> This would then trip the alarm because the server would try to process 'em all miliseconds apart. The spam protection checks the server-side time of each request, so this would show up as if someone with a saner ping just tried to DDOS the server.
> 
> A possible solution is to throttle the verbs and refuse to execute them rather than kick people. The tricky bit is that would still incur server-side load, so could still have DDOSers.
> 
> I don't think making these verbs noninstant would be viable - instant means you can execute this verb alongside other inputs, so it's smoother... I guess an option would be to create alternate non-instant movement commands and some kind of skin-level toggle to let players with high latency switch to them.

What I don't really get is why I've only ran into it after the latest Baymerge, I've been playing with this ping on Urist since mid/late Glloydstation days and haven't really ran into issues until now, unless it's something Bay added recently?

**Comment by scrdest** [comment]
It does not need to be a DDoS, DoS is more likely if anything due to how nightmarish it would probably be to automate connecting to a BYOND server properly. 

But yeah - the main risk is that one or more bad actors could overwhelm the server with requests, especially considering we're not running it on anything particularly meaty.

A system to detect distributed attacks would most likely be unnecessary complexity added on top, and have a lot of the same problems (would you prefer false positives or false negatives?).

**Comment by Glloyd** [comment]
https://github.com/UristMcStation/UristMcStation/commit/47e630f18a7fd61f811ab66c2f08dc2dd664ca4f

i tweaked some of the values here. The problem with actions queuing when the server lags might need something like SSinput to solve completely though.

**Comment by Yantarii** [comment]
I've tried it yesterday and ran into 0-kicking issues, even with Goonchat on which is great, I think it's solved for now for me, but I'll do more testing when we have more pop again

**Comment by CPU-Blanc** [comment]
Has this issue been solved with the new config updates? I've not seen any kicks as of late

**Comment by Yantarii** [comment]
Haven't had a single spam kicking issue since Glloyd changed the config, not sure if @CaraS212 still has issues with it?

**Comment by CPU-Blanc** [comment]
Closing as this seems to have been fixed with the config change. Tag me here if issues arise again and I'll re-open it.
