### ISSUE TITLE
Holodeck Wildlife Simulation doesn't spawn holocarps

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1286]
### Description of issue

Holodeck Carp won't spawn when Emagged, when pressing the wild-life simulation button. Making it useless to emag the Holodeck Computer.

The Holodeck also moves to a blank enviro to spawn.

### Difference between expected and actual behaviour

Holocarp should spawn when pressing the wild-life simulation buttton, which it currently doesn't.

### Steps to reproduce

1. Emag the Holodeck Computer
2. Press Wildlife Simulation Setting
3. Nothing happens.

### Specific information for locating

Holodeck Map (Nerva 5/6 or something similar)
Holodeck Code
Holocarp

### Client version, server revision, & game ID

Current Baymerge

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Bleh. I fixed this before. Must be regressed in the merge. I'll fix it shortly
