### ISSUE TITLE
Antagonist Ambitions don't appear anymore at round end.

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1291]
### Description of issue

Antagonist Set-Ambition and Ambitions in general, don't seem to show up at the end of the round anymore. Meaning we only get the round type, antags (and ckeys) what they bought and last words, missing the ambitions (if they set them.)

### Difference between expected and actual behaviour

Set-Ambition Verb should update your ambition as an antag and show up at the end of the round.

### Steps to reproduce

1. Set Ambition.
2. End Round.
3. No Amibition at the Round End Screen

### Specific information for locating

Ambition Code/Set Ambition Verb, maybe some issues due to us porting last-word and then bay-merging which also had last-words? No idea.

### Client version, server revision, & game ID

Current Baymerge, was not broken on original Master build of Urist.

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by ggermanicus** [comment]
I set one earlier today as an engineer traitored mid-round without issue. It couldn't be a clown thing could it?

**Comment by CPU-Blanc** [comment]
Also observed it working for Wiz. What antag type were you?

**Comment by Yantarii** [comment]
Weird, I'll try it out again
