### ISSUE TITLE
Simple mobs attack exosuits without pilots

### ISSUE THREAD

**Issue by Naxodile** [UristMcStation/UristMcStation#1302]
### Description of issue

Simple mobs will destroy exosuits regardless of who or if anything is inside them.

### Difference between expected and actual behaviour

Less hatred towards unactive pieces of metal

### Steps to reproduce

Spawn exosuit, spawn hostile simplemob, observe

### Specific information for locating

This is due to exosuits being /mob/living subtypes with a default faction of neutral

### Client version, server revision, & game ID

Client Version: 514
Server Revision: [e16a6956a9e107b9070d46043020346113a5325e](https://github.com/UristMcStation/UristMcStation/commit/e16a6956a9e107b9070d46043020346113a5325e) - 070d46043020346113a5325e - 2023-10-06
Game ID: cqa-atjF
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Current code _does_ actually take this into account. 
https://github.com/UristMcStation/UristMcStation/blob/ec61bad64d715d5dac9c9c5532113b704506a5a8/code/modules/ai/ai_holder_targeting.dm#L137-L141

They should only attack empty exouits if their `destructive` var is `TRUE`. What  mob type was destroying an empty mech? I see only zombies and bears should attack empty suits

**Comment by CPU-Blanc** [comment]
lmao nvm I found the issue. PR soon.
