### ISSUE TITLE
Mining drills dont seem to extract gold or silver

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1306]
### Description of issue

Mining drills only seem to extract platinum from precious mineral deposits

### Steps to reproduce

set up drill
significant precious mineral deposit
look inside
only platinuim

### Client version, server revision, & game ID

current as of time of report

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Just double-checking, but do you mean the large mining drill, not the inhand weapon type?
Type paths always help in bug reports

**Comment by CPU-Blanc** [comment]
Looking into it, this might be more of an issue with ore generation. Something is definitely going wrong.
@ggermanicus  looks like in #1250 you reverted a bunch of my ore generation fixes made in #1005. Any reason for these changes?
