### ISSUE TITLE
Top mount SMG still jams

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1310]
### Description of issue

top mount smg from protolathe still jams when loaded with real ammo

### Difference between expected and actual behaviour

it should not do this

### Steps to reproduce

print smg, load with not rubbers, 3 round burst, jam

### Client version, server revision, & game ID

current as of oct 7 2023

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by ggermanicus** [comment]
Same with the HI-2521 SMG. jam_chance is 0 on them, not sure what's up.

**Comment by CPU-Blanc** [comment]
Got a fix for this coming. I'll be bundling it with some others

**Comment by CPU-Blanc** [comment]
Small oversight found that can cause this in edge cases. PR coming shortly
