### ISSUE TITLE
Abolition Extremists have extreme fire rates

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1313]
### Feedback

The hostiles on the slaver base have an insane fire rate. basically will fire the laser at you faster than you can react and will burn through you.

(also theres no air in the base but id have to see if the map even has any breaches.)

**Comment by ggermanicus** [comment]
Gave this a test and as of right now they seem to fire pretty normally.

**Comment by ggermanicus** [comment]
No reproduction as far as I'm aware
