### ISSUE TITLE
Mining gen does not seem to have changed much 

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1326]
### Description of issue

it looks like the scanner still picks up the same readings all over the place, the drill does not seem to pick up lower/mid tier ores such as silver and gold, and wall gen is mostly the same but with 4 pockets of gold ore in stead of 2 at most

![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/a0ad11e4-d5ad-4abd-a211-2ccb0d7981bd)
![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/caf423ba-9c94-4ee8-abb7-8c3fe75fedbd)
![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/bdca80d0-a1d7-4dc6-bcf2-005b638047c5)

### Steps to reproduce

go mining and scan, use mesons or aghost to look at the walls

### Client version, server revision, & game ID

Client Version: 514
Server Revision: ec61bad64d715d5dac9c9c5532113b704506a5a8 - ac9c9c5532113b704506a5a8 - 2023-10-09
Game ID: cqe-djrN

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Already fixed. Server hasn't yet updated
