### ISSUE TITLE
ore scan gen still not fixed

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1336]
### Description of issue

this time everything is just surface materials, all across the asteroid

at least i hope its not just the server having not updated again.
![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/3086ac42-288f-4d0e-9a0e-a307cf8dddbd)

### Steps to reproduce

scan a variety of locations on the asterid

### Client version, server revision, & game ID

Client Version: 514
Server Revision: 3a733b20e8ec271813106ceb08db5d359df047ad - 13106ceb08db5d359df047ad - 2023-10-13
Game ID: cqh-aAYt

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
@scrdest Looks like there's an issue with the noise map. It appears to only start generating until Y64 and below over all maps
