### ISSUE TITLE
Smart Service Revolver starts on lethal despite displaying as stun

### ISSUE THREAD

**Issue by ggermanicus** [UristMcStation/UristMcStation#1347]
### Description of issue

Selecting the smart service revolver from the sidearm kit gets you your revolver but it begins on lethal, despite displaying as stun in examine and icon state.

### Difference between expected and actual behaviour

It's a smartgun that starts on stun, icon state and desc included. It should shoot stuns without having to be cycled first.

### Steps to reproduce

1. Pick stylish option in sidearm kit
2. Shoot gun

### Specific information for locating

/obj/item/gun/energy/revolver/secure
in
/obj/item/gunbox

### Client version, server revision, & game ID

Client Version: 514
Server Revision: 6276d967caef01480a526406638472aaccb68723 - 0a526406638472aaccb68723 - 2023-10-14
Game ID: cqj-a22T
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
So this isn't actually firing lethals. It's actually firing practise rounds amusingly. PR coming soon
