### ISSUE TITLE
airlock buttons under glass

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1361]
### Description of issue

![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/91c08a4c-2b14-4d9b-8eae-129cee710849)
airlock buttons and such appear under glass

### Steps to reproduce

look at airlock
controls inaccessible

### Client version, server revision, & game ID

Client Version: 514
Server Revision: 459b275348172665819d5166c821f071c25dbb74 - 819d5166c821f071c25dbb74 - 2023-10-21
Game ID: cqp-duDY
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by Glloyd** [comment]
there's a few airlocks around the nerva broken like this, mostly the solars, but a couple others.
