### ISSUE TITLE
Roboticists don't get robotics access

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#1374]
### Description of issue

If you join as Roboticist you don't have ACCESS_ROBOTICS

### Steps to reproduce

1. Join as Roboticist
2. Do absolutely nothing else because you're trapped in your spawn room.

### Client version, server revision, & game ID

Client Version: 514
Server Revision: [e236647aa3d86e60a9ca5aaa838ceda09c538976](https://github.com/UristMcStation/UristMcStation/commit/e236647aa3d86e60a9ca5aaa838ceda09c538976) - a9ca5aaa838ceda09c538976 - 2023-11-11
Game ID: cqX-dG7E
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Also adding that the 2 airlocks connecting to cargo from robotics have _both_ `ACCESS_ROBOTICS` and `ACCESS_CARGO`, meaning cargo can access robotics? Seems like an oversight

**Comment by Glloyd** [comment]
fucking area access, always gets me

**Comment by Glloyd** [comment]
> Also adding that the 2 airlocks connecting to cargo from robotics have _both_ `ACCESS_ROBOTICS` and `ACCESS_CARGO`, meaning cargo can access robotics? Seems like an oversight

it actually requires both, not one or the other. one or the other is a nested list.
