### ISSUE TITLE
cant graffiti

### ISSUE THREAD

**Issue by ErrorsWindows** [UristMcStation/UristMcStation#1411]
### Description of issue

normally when you use a sharp object like a screwdriver or a glass shard or a knife or something on a floor or wall it allows you to write a persistent message but I can't
(I have tried using write with blood earlier and I think that still does work, it's just chiseling that doesn't seem to work)

and I did try right clicking https://github.com/UristMcStation/UristMcStation/pull/671

### Steps to reproduce

1. sharp object
2. can't cut floor

### Specific information for locating

https://github.com/search?q=repo%3AUristMcStation%2FUristMcStation%20graffiti&type=code

### Client version, server revision, & game ID

Client Version: 515
Server Revision: [cc40971bd063df88431434211de6e64cfd493b33](https://github.com/UristMcStation/UristMcStation/commit/cc40971bd063df88431434211de6e64cfd493b33) - 431434211de6e64cfd493b33 - 2024-02-17
Game ID: csG-awYT
Current map: ICS Nerva

### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Looks like a missed regression from the baymerge. I see where it's happened
