### ISSUE TITLE
Research borg can't sync with R&D

### ISSUE THREAD

**Issue by ggermanicus** [UristMcStation/UristMcStation#1462]
### Description of issue

The portable destructive analyzer destroys items, then when using the sync option, does absolutely nothing. R&D gains nothing from your destruction. Not tested by another player currently.

### Difference between expected and actual behaviour

Portable destructive analyzer should sync to R&D servers.

### Steps to reproduce

1. Select research module as borg
2. Select portable destructive analyzer
3. Pick something up with it that has levels (like a multitool)
4. Click the analyzer and select Analyze
5. Click the analyzer and select Sync
6. See R&D hasn't updated with any new levels

### Specific information for locating

/obj/item/portable_destructive_analyzer
Research module for cyborg - /obj/item/robot_module/research

### Client version, server revision, & game ID

Client Version: 514
Server Revision: e3aca7784eecadc12ec18f62cc24a9bda04f3401 - 2ec18f62cc24a9bda04f3401 - 2024-04-12
Game ID: ctz-dwMZ
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Cannot reproduce. Scanned materials, uploaded to the network, sync'd the console in RnD to the server and the levels were all there as expected

**Comment by ggermanicus** [comment]
I may be stupid, looks like I missed the crucial 'sync the R&D computer too' step
