### ISSUE TITLE
Gibber message seems to travel through Z-Levels.

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1477]
### Description of issue

The Meat Grinder seems to send a visible message to people in the bar, the level above when it is used.
In the round I was in, myself and Thunderstruck were on the main bar level, and could see red action messages when Ryanwraith put animals in the gibber.

### Difference between expected and actual behaviour

Only people nearby the gibber should see the action message/warning.

### Steps to reproduce

1. Have someone be above the freezer.
2. Have someone else start gibbing something.
3. You can see the message above.

### Specific information for locating

/obj/machinery/gibber

### Client version, server revision, & game ID

Current Baymerge
24/05/2024

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
I cannot reproduce this in my tests. Are you able to replicate this? Is there a chance a floor tile was broken or there was some other form of line-of-sight?

**Comment by Yantarii** [comment]
I'll try to replicate it next time we have people on, I was on the stool that allows you to see into the Kitchen and see the stairs, though it isn't in view still
