### ISSUE TITLE
The autopsy scanner does not work on prosthetic limbs

### ISSUE THREAD

**Issue by ErrorsWindows** [UristMcStation/UristMcStation#1539]
### Description of issue

title

### Difference between expected and actual behaviour

The autopsy scanner is normally available with how_open, normally available with a cut wound such as a surgery incision (a unique organ in the organs system), but because prosthetic limbs don't have wounds you can't cut them with an incision and there isn't an exception made for the open panel surgery - making autopsies impossible on prosthetic limbs or robot people

Not sure if intentional design or bay spaghetti

### Steps to reproduce

1. C*t yourself
2. Scan with autopsy scanner
3. Print and read injuries
4. Open the panel on a prosthetic limb to try the same
5. It says that I have to cut it open first
6. 😔 

### Specific information for locating

Autopsy scanner, prosthetic limbs
https://github.com/UristMcStation/UristMcStation/blob/baymerge-testing/code/game/objects/items/weapons/autopsy.dm#L157

### Client version, server revision, & game ID

Client Version: 514
Server Revision: [ec0d21b6ad2b32ba2fbbf8f982909cd4fe700131](https://github.com/UristMcStation/UristMcStation/commit/ec0d21b6ad2b32ba2fbbf8f982909cd4fe700131) - 2fbbf8f982909cd4fe700131 - 2024-07-26
Game ID: cuW-ayG5 - July 28, 2024
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
I don't know what else you expect? They're prosthetics, of course you can't do an autopsy on them, there's nothing organic to do an autopsy on

**Comment by ErrorsWindows** [comment]
the autopsy is an examination of injury marks and what caused them, a post-death examination, rather than some kind of kidney stone removal that would be unique to an organic organ - a detective oversight?
