### ISSUE TITLE
body bags (and subtypes) are not subject to gravity

### ISSUE THREAD

**Issue by ErrorsWindows** [UristMcStation/UristMcStation#1546]
### Description of issue

title

when you drag it over the elevator it just hangs there, even when you bring it out onto lattice and cut, it would normally make a person or any other item fall when I do that

### Difference between expected and actual behaviour

it's just not right, it works for closets and crates and other storage structures

### Steps to reproduce

1. bring body bag out to the elevator
2. move elevator down
3. move body bag into elevator hole (e.g. cutting a lattice out from under it)
4. it floats

### Specific information for locating

not sure, it could be something related to density? or how objects fall

### Client version, server revision, & game ID

Client Version: 514
Server Revision: [d8b2b102a390c88ee432ca27ee851e73e6c35e48](https://github.com/UristMcStation/UristMcStation/commit/d8b2b102a390c88ee432ca27ee851e73e6c35e48) - e432ca27ee851e73e6c35e48 - 2024-08-02
Game ID: cu1-dBca
Current map: ICS Nerva

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by ggermanicus** [comment]
Wasn't able to reproduce this, bodybags fell into holes just fine for me. The dark icon does a fairly bad job of showing it's down a level, though.

**Comment by ggermanicus** [comment]
No other reproductions or reports of this bug.
