### ISSUE TITLE
Mad Xenomorph Science with Knoxon

### ISSUE THREAD

**Issue by Knoxon** [UristMcStation/UristMcStation#168]
So, you want to do mad science involving xenomorph bodies recovered from the gateway? Great!
Today lets try and switch the brain of this dead xenomorph and this assistant brain!
Having trouble fitting it in the xeno's head because "Brains don't normally go there?", thats fine! Just shove it in the chest, works every time!
Tl;dr. You can transplant human brains into xenos, but not into their heads, into their chest (which works somehow), but unfortunately you can't close your new xenomorph.

**Comment by scrdest** [comment]
@Glloyd commits grabbed now, I believe.

**Comment by Glloyd** [comment]
Once I merge upstream both alien issues will be closed.

**Comment by scrdest** [comment]
I could swear the fixes were in the last one... then again, I was not the one doing the merging, so I guess I might have mixed up the commit dates.
