### ISSUE TITLE
Diona got broke

### ISSUE THREAD

**Issue by Knoxon** [UristMcStation/UristMcStation#176]
http://puu.sh/dyXL0/571f67249d.png
I blame Bay and their stupid aliens

**Comment by internetcritic** [comment]
Zuhayr, why cut down on the Diona snowflake code? They're a whole race, and yes, they're a lot like Xenos in how they evolve, but putting them in with Xenos is just pretty lazy.

**Comment by Zuhayr** [comment]
If you think that a refactor to cut down on redundant code is lazy, then I'm going to assume you're not a programmer.

**Comment by Zuhayr** [comment]
Please feel free to reimplement the garbage monkey descent code that they previously used if you would like to revert the several hours it took me to lazily rewrite them.

When features share functionality, refactoring them to share code is the cleanest and most maintainable way to refactor code. If you think that's laziness, then I'm not sure what to tell you.

**Comment by scrdest** [comment]
That issue is a year ago AND a BS12 issue. I'm going out on a limb it was fixed as well as it ever would.
