### ISSUE TITLE
Staff of Change may morph people into Tajarans

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#182]
Any SoC-able creature hit with the charge from it may turn invisible and lose their UI, and according to Vakothu at least, they are turned into Tajarans, who, due to not being completely removed, cause issues. If you somehow hit the invisible person with another ray, they can be morphed again as normal.

**Comment by Glloyd** [comment]
Hahahahaha, this must've happened on that wizard round last night. I'll look into it, thanks.

**Comment by scrdest** [comment]
Yeah, it did. Matter of fact, I was the wizard.

**Comment by internetcritic** [comment]
I feel like this shouldn't be a problem. The Tajaran is kind of a role for punishment, and those who piss off the wiz enough should be allowed to be turned.

**Comment by scrdest** [comment]
It's not that they become Tajarans, it's that they literally vanish out of existence for damn near everyone involved - wizard, because the person is 100% invisible at all times, and the person, because he doesn't even have a UI.
