### ISSUE TITLE
Time to Merge Bay

### ISSUE THREAD

**Issue by Glloyd** [UristMcStation/UristMcStation#184]
Yup. It'll fix some issues on here. Want to get this done before the next update.

**Comment by Glloyd** [comment]
Will fix #160 and partially fix #159

**Comment by JacobLee1** [comment]
http://i.imgur.com/9BP81Ih.jpg

**Comment by JacobLee1** [comment]
I'll see if I can make the breaker boxes work when you update, if you don't want to.

**Comment by Glloyd** [comment]
Boom. That was easy as fuck. Also, no need, the breaker boxes have been in for a while, they're optional.
