### ISSUE TITLE
New hairstyles broke as fuck

### ISSUE THREAD

**Issue by Knoxon** [UristMcStation/UristMcStation#192]
http://puu.sh/eFn6H/ce5b3e3eca.png
This happens with all the hairstyles from "edgeworth" to "shinobu"

**Comment by Glloyd** [comment]
That's the last time I touch a .dmi. Jesus fuck.

**Comment by Glloyd** [comment]
Easy fix though, just delete the white. I'll do it later if noone beats me to it.
