### ISSUE TITLE
Vampires can infiltrate and rob Central Command

### ISSUE THREAD

**Issue by JacobLee1** [UristMcStation/UristMcStation#193]
We just had a round where a vampire managed to mist form into the Thunderdome and steal an energy axe. They also nabbed the ERT commander's gear from the equipment room.

Wizards, fortunately, can't abuse ethereal jaunt in a similar manner.

**Comment by Glloyd** [comment]
@scrdest

**Comment by scrdest** [comment]
...whaaaa? How did they get *TO* CentComm in the first place? If this was a round-end thing, then it's not much of a bug - you can achieve pretty much the same with, say, a fresh emag, probably.

And while I cannot check it ATM, I'm quite confident in saying that the mist form code is a copypasta of Ethereal Jaunt code, and even still I don't see why Wizards couldn't abuse it the same way.

**Comment by Glloyd** [comment]
Likely hopped on the Arrivals shuttle as it was leaving.

On Tue, Jan 20, 2015 at 3:14 AM, scrdest <notifications@github.com> wrote:

> ...whaaaa? How did they get *TO* CentComm in the first place? If this was
> a round-end thing, then it's not much of a bug - you can achieve pretty
> much the same with, say, a fresh emag, probably.
>
> And while I cannot check it ATM, I'm quite confident in saying that the
> mist form code is a copypasta of Ethereal Jaunt code, and even still I
> don't see why Wizards couldn't abuse it the same way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/193#issuecomment-70618563>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Mist form + space suit means they could go anywhere on the Centcomm
z-level, including the Syndicate base and Vox shuttle. We need to patch
this before someone realizes that.

On Tue, Jan 20, 2015 at 3:47 AM, Graham Lloyd <glloyd9714@gmail.com> wrote:

> Likely hopped on the Arrivals shuttle as it was leaving.
>
> On Tue, Jan 20, 2015 at 3:14 AM, scrdest <notifications@github.com> wrote:
>
>> ...whaaaa? How did they get *TO* CentComm in the first place? If this
>> was a round-end thing, then it's not much of a bug - you can achieve pretty
>> much the same with, say, a fresh emag, probably.
>>
>> And while I cannot check it ATM, I'm quite confident in saying that the
>> mist form code is a copypasta of Ethereal Jaunt code, and even still I
>> don't see why Wizards couldn't abuse it the same way.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UristMcStation/UristMcStation/issues/193#issuecomment-70618563>
>> .
>>
>
>
>
> --
> Graham Lloyd
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Vamps aren't even supposed to be able to stay in space without being hit with sunlight FOR MASSIVE DAMAGE, so a buff to the scorchiness of sunlight could help it. And possibly moving the transit section away from CentComm proper.

**Comment by Glloyd** [comment]
Just tried it as a Wiz, you can't blink or ethereal jaunt on the centcomm z-level. There's likely a z-level check in there that stops them from using it at Centcomm.

**Comment by scrdest** [comment]
You're right - there is a var in the spell, centcom_cancast or something along the lines, that prevents the spell from working on that z-level.

**Comment by Glloyd** [comment]
Aye, same. I'll see if I can get it done later tonight though.
