### ISSUE TITLE
Barber's Scissors Knives causing runtimes

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#206]
runtime error: writing to read-only variable
proc name: generate blood overlay (/obj/item/proc/generate_blood_overlay)
  source file: items.dm,620
  usr: Beau Styles (/mob/living/carbon/human)
  src: Knife (/obj/item/weapon/improvised/scissorknife/barber)

runtime error: Cannot modify null.color.
proc name: add blood (/obj/item/add_blood)
  source file: items.dm,599
  usr: Beau Styles (/mob/living/carbon/human)
  src: Knife (/obj/item/weapon/improvised/scissorknife/barber)
  call stack:

**Comment by Glloyd** [comment]
@TGameCo

**Comment by TGameCo** [comment]
Is this from the merge? I don't remember anything like this during testing

**Comment by scrdest** [comment]
No, it's a local test of my code on the current base, didn't touch them one bit.

**Comment by TGameCo** [comment]
I can't find anything I've done that would do this. Is this only happening with this item or does it happen with other knives? 
The code that borked is this:

    /obj/item/proc/generate_blood_overlay()
	    if(blood_overlay)
	    	    return

	    var/icon/I = new /icon(icon, icon_state)
	    I.Blend(new /icon('icons/effects/blood.dmi', rgb(255,255,255)),ICON_ADD) //fills the icon_state with white (except where it's transparent)
	    I.Blend(new /icon('icons/effects/blood.dmi', "itemblood"),ICON_MULTIPLY) //adds blood and the remaining white areas become transparant

	    //not sure if this is worth it. It attaches the blood_overlay to every item of the same type if they don't have one already made.
	    for(var/obj/item/A in world)
		    if(A.type == type && !A.blood_overlay)
			    A.blood_overlay = image(I)

And this
    	//apply the blood-splatter overlay if it isn't already in there
	if(!blood_DNA.len)
		blood_overlay.color = blood_color
		overlays += blood_overlay
These were all found in code/game/objects/items.dm, on line 599 and 620 (Those were the culprits that the issue talks about

**Comment by scrdest** [comment]
No idea if others bork too, I just found this by complete random dumb luck while stabbing myself with one to test how my new ghetto bleeding-fixers work.

**Comment by Glloyd** [comment]
It's not related to that file unless it's happening on other items. If it's just happening with scissor knives, it's an issue with scissor knives likely trying to apply an improper overlay.

**Comment by TGameCo** [comment]
I never messed with icon overlays on scissors, it is (probably) not my fault

**Comment by scrdest** [comment]
Does not seem to be happening anymore.
