### ISSUE TITLE
Atmospherics doesn't work roundstart.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#214]
When the round starts, all the pumps in atmos are on, even the ones that aren't supposed to be, but the syphon in the mixed air supply tank isn't on, so no air mix gets into the distribution pipes.

**Comment by JacobLee1** [comment]
I forgot to reference this when I opened #250. Requesting DIVINE @Glloyd intervention.

**Comment by Glloyd** [comment]
:heart:
