### ISSUE TITLE
West mining outpost - SMES not charged at round start

### ISSUE THREAD

**Issue by Naverin** [UristMcStation/UristMcStation#223]
The Mining west outpost is the first area to power alarm.  I looked into it further and the outpost only has an APC battery and no SMES charge behind it, so its not able to be used without breaking in.

The airlock requires a good bit of power to cycle 1 person in with solid phoron for the generator and  cant seemly be accomplished by the time you can get some phoron and get out to the outpost.

**Comment by Glloyd** [comment]
I fixed this in one of the S-COM commits.
