### ISSUE TITLE
Gas cooler - Pipe direction

### ISSUE THREAD

**Issue by Naverin** [UristMcStation/UristMcStation#230]
Gas coolers when constructed no longer have the option of using a screwdriver on the circuit board to change the direction of gas hook up to the cooler.

Almost seems random when building them as to which direction it will go

**Comment by Zuhayr** [comment]
If it's based on Baycode the it uses the direction you were facing when you build the machine frame and is intended behavior for upstream.

**Comment by Naverin** [comment]
Thanks!  just tested that out on the server and you are correct.  That worked exactly as you described.

consider this a non bug
