### ISSUE TITLE
Kitchen code, Y U DO DIS?

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#247]
Custom foods need a serious cleanup. Off the top of my head:

- [x] aside from sammiches, which, possibly due to being baycode feature, work pretty fine (with a minor exception), custom food items completely ignore filling color and instead go with eye-bleedingly ugly RGBY colors. I have a suspicion which line of code causes it.

- [ ] sammiches, as well as other custom foods, don't transfer their contents to other custom foods they are added to, instead the whole object creates nested custom foods. While in most cases hilarious, you can easily break reality by adding a max size sandwich onto a slice of bread, collapsing all the contents of the old sandwich into Quantum Deliciousness Storage. Feedback suggests keeping it.

- [ ] grill removes ALL overlays, glitching the graphics for overlay-based foods.

- [ ] oven-based machinery can magically teleport food to and from the user, probably due to the sleep() preceding setting loc without a sanity check for the mob being adjacent.

**Comment by scrdest** [comment]
I figured out why ice cream showed an empty cone icon. @Glloyd you forgot to fix the icon path to point to urist/kitchen.dmi rather that base code kitchen.dmi.

**Comment by Glloyd** [comment]
Could you do that for me?

On Sat, Jul 11, 2015 at 7:44 AM, scrdest <notifications@github.com> wrote:

> I figured out why ice cream showed an empty cone icon. @Glloyd
> <https://github.com/Glloyd> you forgot to fix the icon path to point to
> urist/kitchen.dmi rather that base code kitchen.dmi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/247#issuecomment-120606935>
> .
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Did already. I will have a PR by tomorrow with some changes, just need to test the last changes.


Sent from Samsung Mobile

-------- Original message --------

**Comment by scrdest** [comment]
Should be fixed by #249
