### ISSUE TITLE
When cyborgs pull Broken wooden tiles, they become floor tiles. (Convert metal to wood?)

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#252]
Trivial issue, but for cyborgs only, when they pull wooden, broken floorboards they become floor tiles (the metal ones.) Strangely, when the cyborg uses floor tiles on the same spot, it becomes a broken wooden tile. When a crew member destroys the broken wooden floor tile, it becomes wood planks. The cycle can be repeated.

**Comment by Glloyd** [comment]
That's a weird fucking bug. I'll see if I can reproduce it.

**Comment by scrdest** [comment]
Probably a bungled icon_state setting somewhere.

**Comment by Skeeve2** [comment]
This also happens with carpets.

**Comment by scrdest** [comment]
Fixed in the Bay pull, AFAIK.

**Comment by Glloyd** [comment]
should be fixed by #277
