### ISSUE TITLE
General map oversights

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#255]
- [ ] Two air alarms in the morgue
- [ ] Two general radio's in the firing range
- [ ] Cafeteria has 2 fire extinguishers
- [ ] Hydroponics back room has no scrubbers or vents
- [ ] Xenobiology examination room has no scrubbers or vents
- [ ] Psychologist newscaster is inaccessible
- [ ] Engineering tool storage newscaster accessible from both sides of the wall (Happens only 1/2 of the time..?)
- [ ] Engineering tool storage has no scrubber
- [ ] Two carpets under North Chapel doors

**Comment by Skeeve2** [comment]
Added one

**Comment by Skeeve2** [comment]
IT KEEPS PILING UP

**Comment by Glloyd** [comment]
Pool has a vent, I'm looking at it right now.

**Comment by Skeeve2** [comment]
Confirmed, oversight on the oversight.

**Comment by Glloyd** [comment]
I'll fix some of this in #277 if not all.
