### ISSUE TITLE
Folding hazard vest has no sprite (Or completely unintended)

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#256]
Folding a bandana from a hazard vest has no sprite, and therefore cannot be picked up or interacted with.

**Comment by scrdest** [comment]
...how did you even fold a hazard vest? I don't think it's an intended feature.

**Comment by Skeeve2** [comment]
Right click hazard vest - "Fold Bandana"
Places TWO on the ground and one in your hand, all are invisible so it appears like you have an empty hand.

**Comment by Glloyd** [comment]
The sprite must've been moved. I'll look into it when I get home.

**Comment by Glloyd** [comment]
It was an old feature I put in for Knox.

**Comment by Glloyd** [comment]
"look into it when i get home" uh huh
will be fixed in #277
