### ISSUE TITLE
Beepsky "report arrest" does nothing

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#258]
Title, it SHOULD be saying in the sec channel where an arrest was preformed, but doesn't.

(Haven't been able to test quite yet.)

**Comment by AseaHeru** [comment]
Its worked for me. Huh.

**Comment by scrdest** [comment]
Still an issue?

**Comment by Skeeve2** [comment]
I'll have to check


On Saturday, February 6, 2016, scrdest <notifications@github.com> wrote:
> Still an issue?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/_sOfv_TWAyZ2x16cS7KzBhammpO05umGojxzm3l9vW9fjxzynAA7lQ5VHt5kedubmNSOWC7oB_zlNMFoxLBI8yVbltKI313wKqL5P6rQjYWk4I_32m1B23MdxY8c96-L2E9JSxDGchxCJqjNZt4QNlw1XaSSpQ=s0-d-e1-ft#https://github.com/notifications/beacon/AB5tvkzvqxCKKbeRVbLWeXiNd0iAs9eWks5phlFpgaJpZM4FexY9.gif
>

**Comment by Glloyd** [comment]
This has been fixed.
