### ISSUE TITLE
Vines grow faster then you can cut them

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#260]
Balance issue, vines are ny impossible to stop. To make matters worse, you have a very tiny clicking space to hit the smaller ones. As soon as you destroy a large vine, another vine will appear below it. In any space larger then 4x4 no matter how many crew members you have it's impossible to stop without pete (The goat.)

Sort of hilarious that no matter what you need the goat or more, but can get out of control and take over the whole station if it spawns in an area where no crew members are present, and beepsky starts opening doors.

**Comment by scrdest** [comment]
There's an update to the way vines behave in the Bay pull. Even if it doesn't fix it, it shouldn't be touched for now.

**Comment by Skeeve2** [comment]
Closing then.
