### ISSUE TITLE
Emergency shuttle can be called during an Scom round.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#264]
This is where we report S-com bugs, right?
If someone joins in as a drone during a S-com round, they spawn station-side, and can call an emergency shuttle, presumably prematurely ending the round.

**Comment by scrdest** [comment]
Should be as simple as extending the borg latejoing to emergency drones or shutting down respawn in setup.

**Comment by Vakothu** [comment]
Yeah, shutting down the maintenance drone spawners during Scom would probably be the easiest way to fix it.

**Comment by scrdest** [comment]
Fixed in #522 (also ERT call disabled likewise).
