### ISSUE TITLE
2-tile doors do not rotate properly

### ISSUE THREAD

**Issue by dore0062** [UristMcStation/UristMcStation#266]
2 tile doors don't rotate properly, when facing north/south they work, but when east/west it's collision is still north/south, so you can walk through the door.

**Comment by scrdest** [comment]
How did that even come into play?

**Comment by Skeeve2** [comment]
I was making a 2-tile door for medbay, so I stole one from the bridge.

**Comment by CPU-Blanc** [comment]
Old issue. Has since been fixed.
