### ISSUE TITLE
A couple Scom bugs.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#267]
When a borg spawns during an Scom round, when they're warped several objects essential for a borg's operation are removed from their contents, including their power cell and camera.

When an Scom mission ends, people in cryotubes, lockers, and cloning pods are also warped to the shuttle, I assume this is because when someone is inside something, they're technically on zlevel 0.  This includes warping the brain-mob out of someone's decapitated head, which explains the brains with eyes you sometimes see arriving at the ship teleporter.

**Comment by scrdest** [comment]
Fairly sure both should be fixed now.
