### ISSUE TITLE
Maze Mission - Last teleporter does not teleport to correct location

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#268]
![teleporterinquestion](http://i.gyazo.com/5716d0726648b88629e50811b12083de.png)

If you step into the teleporter (above) it should teleport you to the end where The Director is, however, it instead teleports you to a space outside the maze, making leaving the z-level impossible.

**Comment by Glloyd** [comment]
Haha, I know exactly how and when this happened and I'm surprised it's taken this long for a bug report. Thanks.

**Comment by Vakothu** [comment]
In addendum to this, the teleporters that spawn when you take the fake diamond also lead you to space.

**Comment by Glloyd** [comment]
This should be fixed in #277
