### ISSUE TITLE
SCOM clowns still have their guns blow up in their hands.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#269]
If you join as a clown during SCOM, the clown-effect of guns being able to blow up in your hands isn't removed.

**Comment by Nienhaus** [comment]
Feature.

**Comment by JacobLee1** [comment]
They're permanent rookies. Feature. :+1:

**Comment by Glloyd** [comment]
I meant to remove this when I made clowns psionic ops. Honk.

**Comment by Nienhaus** [comment]
Don't fix it.

**Comment by Glloyd** [comment]
It'll be indirectly fixed when Galactic Crisis comes around because of a refactor of how role assignments are done.
