### ISSUE TITLE
Security drones destroyed in single taser shot

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#278]
Doesn't seem right, beepsky, etc, takes single taser (not laser) shot to destroy.

**Comment by Glloyd** [comment]
I wonder if this is fixed in the update. Will have to test this.

**Comment by Skeeve2** [comment]
fixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixedfixed
