### ISSUE TITLE
Using welding tool on compromised fire axe cabinet with fire axe inside causes it to disappear

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#279]
Title. By "Disappear" I mean the ENTIRE CABINET.

**Comment by scrdest** [comment]
That's bizarre. Steps to reproduce?

**Comment by Skeeve2** [comment]
It occurred when I was a cyborg, I used a lot welding tool on a compromised
fire axe storage with the axe still inside. The icon disappeared, the
fireaxe cabinet was still "there" just with no icon.

On Tuesday, August 18, 2015, scrdest <notifications@github.com> wrote:
> That's bizarre. Steps to reproduce?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/uLx149765trWBq_JpU6l1J8s4RoiaP29CAFOUfQdqxkXl3KNpK4ufwnSup4fqivXGLTxXuz98zjztFmVk1ZpoManCsY7jUeTvgBYfIGqF_3-18yPhir9Bme4mUMhgulIL4UwGAdiJFtVAqR5MN7wWkisZQVR3Q=s0-d-e1-ft#https://github.com/notifications/beacon/AB5tvoTJrRlJGT6x9POgS6lZm6HugJTPks5oosh3gaJpZM4FtRFh.gif
>

**Comment by scrdest** [comment]
Ah. That's kind of an important detail that you were a borg.

**Comment by Glloyd** [comment]
Can this still be reproduced?

**Comment by Skeeve2** [comment]
fixedfixedfixedfixedfixed
