### ISSUE TITLE
Holodeck burn test is COMPLETELY FUCKED

### ISSUE THREAD

**Issue by Flip-Sandwich** [UristMcStation/UristMcStation#280]
ZAS + Insane amount of fire pressure = RIP a quarter of the station

It's way too powerful and needs to be toned down or removed

**Comment by Flip-Sandwich** [comment]
Like, holy balls, this is literally a two click ROUND ENDER http://i.imgur.com/GGBzzPU.png

**Comment by Skeeve2** [comment]
Already reported in #273

**Comment by Flip-Sandwich** [comment]
oh :V
