### ISSUE TITLE
Bomb test range not firing objects correctly

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#282]
Mass driver will shoot the object, but it will stop upon hitting space. Still works for mobs though, unsure if fixed in new update.

**Comment by liction15** [comment]
This has more to do with ZAS pushing the bomb out before the mass driver can launch it. If you seal off the launcher, empty the air and use a disposals chute to place the bomb on the mass driver it works fine.

**Comment by Glloyd** [comment]
Yeah, I'll fix it in #277
