### ISSUE TITLE
Cortical borer sometimes causes both mobs to delete

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#284]
In rare cases (three times witnessed as of this bug report) a cortical borer attempting to parasite onto a human will completely delete itself and the mob along with all items at seemingly random. I have no idea what causes this.

**Comment by scrdest** [comment]
Most likely a runtime error.

**Comment by scrdest** [comment]
Should be fixed in the merge.

**Comment by Skeeve2** [comment]
fffffffffffixed
