### ISSUE TITLE
Using chameleon projector in bar closet teleports you in any direction

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#286]
You can also drag the closet around and use it anywhere. Can be used to go through mass doors, walls, etc.

Not sure the details, ask mapleguy555. Suggested to report to baystation 12 as well.

**Comment by Skeeve2** [comment]
Update : Close locker, then activate chameleon projector, then step in any direction and it will teleport you on top of the tile.

**Comment by scrdest** [comment]
Just for the sake of sanity, unless it's specifically a bug with a Urist/non-Bay item or system, report bugs to BS12 tracker and just say it's from a downstream and may be fixed.

If it's a Baycode issue, we could fix it locally, but a) that means we then must maintain the code, which means even longer and more painful update process, b) is kinda pointless to lock Bay out of fixes, and c) chances are the Bay coder responsible for overlooking the bug understands the code better and can fix it quicker than us.

**Comment by Skeeve2** [comment]
Still an issue even on Polaris, which is interesting. Seems like a fix might be in order.
