### ISSUE TITLE
Round Join Failure

### ISSUE THREAD

**Issue by DXblueshadow** [UristMcStation/UristMcStation#287]
So I was trying to join a round earlier today when I came across an odd glitch I had never seen before. Specifically I had just created my first Diona character for the server and saved him into slot one, overwriting the previous one, and when I attempted to join an in session game as a Bartender the glitch occurred. While the HUD icons and status had loaded, they were overlaying the lobby picture which continued to remain regardless of where I tried to move. (Honestly I don't think I even was moving) Adding to this is when I tried to interact with my inventory I would keep getting a message to 'Stop attacking people at spawn' and reconnecting did nothing to fix this. Afterwards I attempted to ghost upon which I was able to move out from under the logo, but then trying the re-enter corpse command informed me that I apparently didn't even have a body, afterwards the ghost seemed to function properly.

**Comment by Glloyd** [comment]
This is weird as fuck, I'll try reproducing it after the merge is done.

**Comment by scrdest** [comment]
Reopen if this pops up, but considering the OP barely exists here and can't reproduce...
