### ISSUE TITLE
Broken sprites general

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#294]
Put broken sprites here

- [x]   Robotics labcoat is letters.
- [ ] Shooting targets are space.
- [x] kimono 
- [ ] corporate security uniform

**Comment by Mark9013100** [comment]
IIRC, shooting target sprites have been bugged for a loooong time.

**Comment by liction15** [comment]
The kimono as well as the school girl outfit are broken

**Comment by Glloyd** [comment]
@scrdest re the kimono, it's another of those fucking custom items

**Comment by Mark9013100** [comment]
Last I checked, the corporate security uniform was broken.

**Comment by scrdest** [comment]
@Glloyd well, it's just a matter of pointing it to the old_bay_custom_icons for now.

**Comment by Glloyd** [comment]
fixed kimonos

**Comment by scrdest** [comment]
Fixed?

**Comment by Skeeve2** [comment]
fixed
