### ISSUE TITLE
Mentors have werid permissions

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#295]
Mentors cannot use JMP, for example. Will update with everything missing.

**Comment by scrdest** [comment]
Not a bug.

**Comment by Glloyd** [comment]
But it is something unintentional that was lost in the merge.

On Sat, Feb 6, 2016 at 3:36 PM, scrdest <notifications@github.com> wrote:

> Not a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/295#issuecomment-180860216>
> .
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Yeah, but that just needs to edit the config to make all the mentors mods again.

**Comment by Skeeve2** [comment]
Fixed a long time ago
