### ISSUE TITLE
Blueshield still unable to spawn with holsters

### ISSUE THREAD

**Issue by andersonconagher** [UristMcStation/UristMcStation#297]
Your current job or whitelist status does not permit you to spawn with holster, hip!

It's a sad state of affairs.

**Comment by scrdest** [comment]
Blueshield is not a BS12 job, no wonder. Probably can't do much while keeping compatibility.

**Comment by Glloyd** [comment]
I'll take a look at the code.

**Comment by Glloyd** [comment]
fixed
