### ISSUE TITLE
Blueshield begins play with an Admiral and Captain ranking uniform

### ISSUE THREAD

**Issue by andersonconagher** [UristMcStation/UristMcStation#298]
That's a NanoTrasen Officer's Dress Uniform. It is a normal-sized item.
Gold trim on space-black cloth, this uniform displays the rank of "Captain." is the jumpsuit Blueshields begin the game with.

   That's a NanoTrasen Officer's Dress Uniform. It is a normal-sized item.
Gold trim on space-black cloth, this uniform displays the rank of "Admiral." is the jumpsuit found in the locker.

I mean unless you want Blueshield-Admirals. Why not.

Also this is super minor why am I even.

**Comment by Glloyd** [comment]
Fixed
