### ISSUE TITLE
Xenomorph larva spawn unable to ventcrawl

### ISSUE THREAD

**Issue by zty8212000** [UristMcStation/UristMcStation#299]
Out of the box, xeno larvas are stuck where they are, because they can't ventcrawl. This looks to be caused by the hivenode organ, or rather, the fact that hivenode is also in the contents list. Deleting it from the contents list has no apparent effect, and allows the larva to crawl

**Comment by Glloyd** [comment]
Yeah, there was some fix commits from Bay I missed. I'll be merging those in tomorrow

**Comment by Glloyd** [comment]
Will be fixed by #302
