### ISSUE TITLE
New Issues (One last one)

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#300]
**Science Outpost**
- ~~South-most transit tube goes straight into a wall, looks like a mapping error.~~
- ~~The random asteroid generation can breach a hole into the Outpost,  at the north-most point of the east hallway~~

**Atmospherics**
- ~~The syphoning vent in the 3x3 area for air to the south starts off, making no air flow into the distribution pipes~~
- ~~The SMES for the APC still starts with input off, running out of power fairly soon after roundstart.~~

**Engineering**
- ~~Door directly south from the CE's office is placed on a wall.~~
- ~~Radiation Collectors aren't close enough to reliably draw power from the Singularity. //they are, it just has to be a stage 3~~
- **~~The singulo can die down to an immobile stage 2 3x3 singularity while one tile out of range of the particle accelerator.~~** //should be fixed
- (Bay Change?) Vents seem to take a lot longer to move air now.
- ~~(Bug?) Emitters for the singularity do not start anchored. //intentional, they need to be set up.~~
- ~~(Bug?) Center Pieces of the TEG don't start anchored either.~~
- (Oversight?) There's no sensor on the Engine Output power-net.
- ~~(Oversight?) The main SMES for the Supermatter Engine Room APC and Singularity Emitters have Output set, by default, to twice as much as their input.~~

**Science**
- ~~Monkeys, roundstart or made from cubes, are incapable of being used for genetic research~~. //looking into this //covered by a separate PR; this is not specific to cube monkeys, it's a bug with Genetics as a whole.

**Maintenance**
- ~~(Bug?) Several hidden doors have been removed, including the one to the Party Room, to the ghetto hydroponics, to the paper-craft room, to the ghetto medbay, etc...~~

**Verbs**
- Hear/Silence Heartbeats toggles on and off OOC instead.

**Misc**
- ~~Drone Fabricator on the station is still tagged "Exodus".~~
     - ~~_Bay added a drone fabricator to the derelict, it's your choice to do so here, or not._~~
- ~~The asteroid at the derelict that the clown shuttle crashed into is just the "mask" for random mine generation.~~
- ~~Bananium spawns in away missions again, as a "NO SPRITE" tile.~~
- ~~The server's database isn't set up, preventing age-checking of players among other things.~~ Seems to be fixed.
- In character creation menu, most of the underwear and undershirt options don't show up.  They all show up properly once you're in game, ~~minus the "blue shirt" undershirt, which shows up as the feminine tank top.~~
- (Bug?) Languages have lost the specific colours, perhaps the fonts too, making it harder to tell which one is being spoken.
- ~~(Bug?) Pun-Pun spawns as a regular monkey.~~

**Comment by Glloyd** [comment]
weird, the hidden doors were there when i tested. Do you mean there was just plating there or what? because they show up as a regular wall now until you click on them. @scrdest I knew there was something up with the heartbeat.

**Comment by Vakothu** [comment]
I was ghosting around and there just were no hidden doors.

**Comment by scrdest** [comment]
Ah, you asked me to check if it worked (which it did, for me), I didn't even think it may toggle OOC too.

**Comment by Glloyd** [comment]
#300 holla

**Comment by Glloyd** [comment]
Fixed most of these.

**Comment by Glloyd** [comment]
Okay, these are all fixed, or covered under other bug reports.
