### ISSUE TITLE
Botany stuff

### ISSUE THREAD

**Issue by Werty892** [UristMcStation/UristMcStation#303]
Issue 1:No rolling papers. What's the point of drying your things if you can't blunt em?

Issue 2:All trays have a light level of 0 lumens, despite being in the light.

Edit: We don't even have drying racks AAAAAAAAAAAAAAAAAAAAHHHHHHHHH

**Comment by Glloyd** [comment]
Added a drying rack to the map, re issue one we'll need to add those, I can't find them in the code.

**Comment by scrdest** [comment]
They weren't added in that commit on BS12. They might've been intended to be added in a separate PR, IIRC, but then, well, Bay coderbus lost its wheels.

**Comment by Glloyd** [comment]
i think that's all. good shit.
