### ISSUE TITLE
Maze awaymap runtime errors!

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#305]
runtime error: Division by zero
proc name: New (/obj/effect/plant/New)
  source file: spreading.dm,120
  usr: null
  src: the glowshrooms (/obj/effect/plant)
  call stack:
the glowshrooms (/obj/effect/plant): New(the floor (17,35,7) (/turf/unsimulated/floor), glowshroom (/datum/seed/mushroom/glowshroom), null)
the trap (/obj/effect/step_trigger/trap): New(the floor (17,35,7) (/turf/unsimulated/floor))
/dmm_suite (/dmm_suite): instance atom(/obj/effect/step_trigger/trap (/obj/effect/step_trigger/trap), /list (/list), 17, 35, 7)
/dmm_suite (/dmm_suite): parse grid("/obj/effect/step_trigger/trap,...", 17, 35, 7)
/dmm_suite (/dmm_suite): load map(maps/RandomZLevels/maze1.dmm, 7)
createRandomZlevel()
/datum/controller/game_control... (/datum/controller/game_controller): New()
: New()

and another one at 15,75,7, otherwise identical.

Tested on the latest Urist master.

**Comment by Glloyd** [comment]
I've got a big commit of map fixes coming today, so I'll add this to it.

**Comment by Glloyd** [comment]
Fixed
