### ISSUE TITLE
SCOM - No jumpsuits, no squad indicator, no ability to open the squad doors, and we all collapse after 5 minutes.

### ISSUE THREAD

**Issue by andersonconagher** [UristMcStation/UristMcStation#307]
SCOM rounds spawn you without jumpsuits or ID, no one gets the squad indicators at the top right of their sprites and no one can open the arming doors by any means, including smash and crowbar.

After about five minutes, everyone suddenly takes massive toxins and brain damage, starts to suffocate, becomes unknown, collapses, goes blind... and is left in a sort of catatonic state where they can talk but not actually stand or do things.

Latejoiners take about one minute to succumb to this... whatever it was also. The soldiers don't seem to die from whatever they have too.

**Comment by Glloyd** [comment]
Let me just note that this is the best bug report ever, and I'm looking into it.

**Comment by scrdest** [comment]
The suffocating+toxin thing has also happened on the Train eventmap, but was fixed by Rejuving the affected mobs. Probably related to unsimulated turfs somehow.

**Comment by scrdest** [comment]
OK, Vakothu figured this out. The teleportation/reequip code on both TrainTime and SCOMTime strip out all the organs from the affected humans - including the brain, hence the 200 brain damage, and liver, hence Tox damage, and so on.

**Comment by Glloyd** [comment]
wuuuut. Okay, we'll just have to figure out how not to make it strip out
the organs.

On Sun, Feb 21, 2016 at 12:45 PM, scrdest <notifications@github.com> wrote:

> OK, Vakothu figured this out. The teleportation/reequip code on both
> TrainTime and SCOMTime strip out all the organs from the affected humans -
> including the brain, hence the 200 brain damage, and liver, hence Tox
> damage, and so on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/307#issuecomment-186871073>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Okay, that should fix it probably. I realized the issue in the middle of a lecture, so I just used Github's online editor.
