### ISSUE TITLE
Singularity Engine Range Issues

### ISSUE THREAD

**Issue by zty8212000** [UristMcStation/UristMcStation#308]
The particle accelerator for the singularity engine can't hit the singularity if it's three+ tiles away from the rightmost edge. Additionally, the radiation collectors can't collect power from a singularity in most positions within the field. The particle accelerator issue could be fixed by just increasing the length the bullets continue for; the collection issue could be at least partially fixed by moving them closer to the singularity (If not putting them outright in space)

**Comment by Vakothu** [comment]
Note, the range issue is only if the PA is at power 0, which is where it should stay.

**Comment by Glloyd** [comment]
Think this is fixed. Should be live on the server soonish.

**Comment by Glloyd** [comment]
Let me know if this is still an issue after the update.

**Comment by scrdest** [comment]
I've had reports that it was fixed.
