### ISSUE TITLE
Forcefeeding pills is instant.

### ISSUE THREAD

**Issue by andersonconagher** [UristMcStation/UristMcStation#309]
So yeah. Instant forcefeeding, instant effects, instant.

**Comment by scrdest** [comment]
Quite likely not a bug, will have to investigate.

**Comment by Glloyd** [comment]
Still, not intended behaviour for Urist imo.

On Mon, Feb 8, 2016 at 9:20 AM, scrdest <notifications@github.com> wrote:

> Quite likely not a bug, will have to investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/309#issuecomment-181393269>
> .
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Yeah, it turns pills into pretty much parapen-tier ggnore weapons. Im ded pls nerf, but still true.

**Comment by Glloyd** [comment]
Fixed
