### ISSUE TITLE
Air pump unable to take in air from environment or tank

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#310]
The pullable mobile air pump doesnt seem to be able to suck in air from the environment or from a tank. Its able to still blow air out into tanks or the environment so there's that as well as take air in from a port. Kinda a huge deal for toxins, otherwise it wont affect much other things until its fixed.

**Comment by Nienhaus** [comment]
That was quick.

**Comment by liction15** [comment]
I played on baystation and this appears to be either intended behavior or an unfixed bug.

**Comment by liction15** [comment]
I am stupid i figured out the problem. Bay seems to have changed the ui so its no longer the target pressure of the air pump but rather the target pressure of the tank/enviroment. Ill close this.
