### ISSUE TITLE
Genetics acting up

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#314]
Any human type mob put in the DNA scanner yields an ingame error like a Husk or mob with no DNA (DNA structure is ruined beyond recognition etc etc) until they are irradiated (targetted or pulse).

Monkeys have only 27 SEs instead of full 50; editing the 27th SE humanizes them in that they get 50 SE blocks, but remain monkeys.

Spawned humans and monkeys humanized by the method above both have every single SE block set to 000, but UI are untouched and properly randomized.

**Comment by Mark9013100** [comment]
IIRC, monkies were changed to a human subspecies long ago-ish on baycode.

**Comment by scrdest** [comment]
Yes, they were, and it's part of the problem - I know the humanization not being a thing is a Bay issue as well - but since BS12 axed genetics (the code is still there, but it's excised from the map) it seems like nobody noticed it broke at some point.

**Comment by CPU-Blanc** [comment]
As genetics has essentially been removed by upstream, is this worth keeping open? A full re-work is probably required at this point if we wanted to re-add genetics

**Comment by scrdest** [comment]
Not for the issue in question at least
