### ISSUE TITLE
CE's rig missing modules (Bay Change?)

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#315]
The CE's back-worn rig is missing the modules it had before the update, and it no longer requires CE access to activate.

**Comment by Mark9013100** [comment]
This is probably the 'empty' version of the RIG.

**Comment by Glloyd** [comment]
Yeah, I noticed that a couple days ago playing as CE, should be fixed by the weekend, there'll be a big fix update.

**Comment by Glloyd** [comment]
Fixed
