### ISSUE TITLE
Any antag that can choose appearance can choose any race.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#318]
Including ones that probably aren't supposed to be avaliable, like undefined, which I assume was originally Tajaran, and all the xenomorphs.
[Menu the wizards get on roundstart](http://i.imgur.com/JtGx86d.png)

**Comment by liction15** [comment]
i dunno i kinda like the idea of alium wizards but yea it is weird. I believe ERT has the same issue.

**Comment by Vakothu** [comment]
Yeah, the problem I see with alium wizards is that they could be used for powergaming, they're smart enough to use magic, so they're smart enough to know that they're weak to lasers, and grab the ablative, the reflect plus the miss chance would make them very hard to kill.  With the no-robe needed power, they'd have three spells, and they wouldn't need to grab magic missile, as they have neurotoxin.

**Comment by liction15** [comment]
i can also confirm nuke has the same issue as well

**Comment by Glloyd** [comment]
Confirming that ERT has the same issue.

**Comment by Vakothu** [comment]
Also confirming that Ninja can do this too, I'm assuming it has to do with the appearance editor, so changed the title to reflect that.

**Comment by Glloyd** [comment]
Alright, going to try to fix this in the next couple days, I had a super busy week last week, but I should have some time this week.

**Comment by scrdest** [comment]
[BS12 reference issue 1](https://github.com/Baystation12/Baystation12/issues/11284)
[BS12 reference issue 2](https://github.com/Baystation12/Baystation12/issues/9552)

**Comment by scrdest** [comment]
[Open BS12 issue ATM.](https://github.com/Baystation12/Baystation12/issues/11086)

**Comment by Glloyd** [comment]
Finally fucking fixed.
