### ISSUE TITLE
Vampire Turn power not working.

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#319]
Followup to #312 - the fix (adding the call to the old snowflake proc dealing with adding the actual mind/vampire, powers and icon under add/create_antag rather than update_antag_mob (why I used it I don't even) managed to address the issues with gamemode spawning the antag on roundstart, but the Turn power still takes the 500 blood but doesn't properly add the target to antags nor vamps them properly via add_antag call in the handle_vampirize proc.

Since the antag refactor is a mess of procs with almost identical purpose and barely documented (guess what's the difference between add_antag, add_antag_mind and create_antag, for example), I don't know if I'll be able to fix this on my own before I get some kind of minor aneurysm from figuring out the system, so I'd be obliged if you could take a peek at the add_antag call @Glloyd

**Comment by liction15** [comment]
i remember a round when a vampire successfully turned me and i showed on the antag list at round end so im not sure if this is a current issue or if this is to fix something related to turning.

**Comment by scrdest** [comment]
When admins were on, most of the vamps asked the admins to manually add the person to antagonists, so it might have been that. There's a message you get when you get turned, I'll post it later.
