### ISSUE TITLE
Underwear icon issues

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#320]
All underwear below Mankini and undershirts below white shirt in their respective lists do not render in the character preview, and AFAIK in-game either - it just looks like you picked none. NT boxers put a 'Unable to open cache file' error on the first pick, but didn't on the further attempts.

**Comment by Glloyd** [comment]
They show up in game, but not in the character preview.

On Fri, Feb 12, 2016 at 12:38 PM, scrdest <notifications@github.com> wrote:

> All underwear below Mankini and undershirts below white shirt in their
> respective lists do not render in the character preview, and AFAIK in-game
> either - it just looks like you picked none. NT boxers put a 'Unable to
> open cache file' error on the first pick, but didn't on the further
> attempts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/320>.
>



-- 
Graham Lloyd

**Comment by CPU-Blanc** [comment]
Old issue. Has since been fixed.
