### ISSUE TITLE
BS12 broke ranged simple_animals

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#321]
More of an announcement than a report, but simple_animals cannot ranged attack, currently. They make the attack sound and drop bullets, but don't fire any projectiles.

It's a known bug on BS12 and dev has already fixed that. It *may* cause runtimes.

**Comment by Glloyd** [comment]
we have different simple_animal code than bay, so that's on our end.

**Comment by Glloyd** [comment]
i think i know what's up, i'll look at it.

**Comment by Zuhayr** [comment]
Projectile code was significantly changed and simple animals were never updated to it until recently.

**Comment by Glloyd** [comment]
fixed in #322

**Comment by scrdest** [comment]
Reopening; I think I missed the changes in projectile.dm, but this time I'll test it myself first.

**Comment by scrdest** [comment]
I think I figured this out; the bullets fired by the simple_animals have a null shot_from var; restoring that to a valid (mob, in my experiments) reference makes them launch properly (though manually proccalled, they didn't impact).

Consistent with that, bullets targetting the firing mob (in launch) impact the firing mob properly, since if the target and source are the same, the whole process is circumvented.

**Comment by scrdest** [comment]
Fixed. It was part that, part the code I ripped from Bay being stupid in the launch call, runtiming because it couldn't find the loc of the mob "chest".
