### ISSUE TITLE
Maploader lagginess

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#341]
Unlike pre-update, the maploader causes horrifying, connection-dropping lag on the server. 

If we didn't pull code from March before the latest updates, it's probably caused by the load_speed removal in dmm_suite.dm, otherwise... weird shit?

**Comment by Glloyd** [comment]
that's probably it.

**Comment by Glloyd** [comment]
From testing, I believe this to be the reason why the server takes so long to restart.

**Comment by Glloyd** [comment]
This is super critical.

**Comment by scrdest** [comment]
Another thing adding to the restart seems to be the asteroid generation, which takes around 50s alone.

**Comment by Glloyd** [comment]
Should be fixed. I tested it locally and load times were down under a minute again.
