### ISSUE TITLE
Toggle Heartbeat is super busted.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#345]
When trying to figure out how to remotely change peoples preferences, (Specifically to fix Gale212's chat problem), I noticed that SOUND_HEARTBEAT in setup.dm is set as 65535 (1111111111111111 in binary), instead of 65536 (10000000000000000 in binary), so toggling heartbeat instead toggles ALL other preference flags, instead of just the heartbeat, causing mass chaos. This is also probably the reason Mapleguy555 constantly keeps getting debug messages.

**Comment by Glloyd** [comment]
sheeeeeeeit
