### ISSUE TITLE
The ninja spawns on the title screen when Ninja is voted.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#347]
Haven't looked into this, but when a ninja round is voted, the ninja spawns on the title screen and stays there, never being warped to the station proper.  If I had to hazard a guess, I'd assume there's no ninja spawn-points in the map, don't expect it to be that simple, though, it's just my random guess.

**Comment by scrdest** [comment]
It's an issue BS12 had too, it might be fixed in the latest code.

**Comment by Glloyd** [comment]
Likely just a case of a missing landmark, I'll look into it.

**Comment by scrdest** [comment]
[BS12 reference issue 1](https://github.com/Baystation12/Baystation12/issues/11284)
[BS12 reference issue 2](https://github.com/Baystation12/Baystation12/issues/9552)

It's a silly code oversight if it's the one from 2 (likely, the fix is from October), will edit online in a sec.
