### ISSUE TITLE
Hydroponics is Buggy

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#349]
If you try to water the plant, it goes into the plant as a reagent, not into the tray. Also unable to replace the nutriment in the tray.

**Comment by scrdest** [comment]
Worked for me. Nutriment sloooowly upped, but worked too.

**Comment by cgale212** [comment]
Sprayed a whole thing of plant-b-gone and the plant was still healthy. From the plant analyzer: - plantbgone, 100 unit(s). I believe if you try to add fertilizer to a tray with no plant it will tell you the tray is full.

**Comment by liction15** [comment]
Hydroponics is still broken which is a shame as it makes xenobotony very hard to do for long period of time as well as hydroponics.

**Comment by Glloyd** [comment]
should be fixed
