### ISSUE TITLE
HoS's energy gun loses it's sprite when it's mode is changed.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#354]
Looking at the code, this is because it changes to the sprites energykill and energystun, when it should be changing to senergykill and senergystun.

**Comment by scrdest** [comment]
Duplicate of #328. Odd, because it was supposed to have been fixed. Might have accidentally gotten reverted somewhere.

**Comment by Glloyd** [comment]
Fixed again
