### ISSUE TITLE
Wet floor stays wet forever.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#355]

**Comment by scrdest** [comment]
https://github.com/Baystation12/Baystation12/issues/11962

**Comment by Zuhayr** [comment]
Not sure if it's the same bug, but: https://github.com/PolarisSS13/Polaris/pull/764

**Comment by scrdest** [comment]
*Should* be fixed.

**Comment by Vakothu** [comment]
Fixed some time ago, not exactly sure when or how.
