### ISSUE TITLE
Mining outpost airlock problems

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#357]
the right side mining airlock seems to not be able to pressurize properly after the second or third time as it seems to run out of air forcing people to have to force it open.

**Comment by Glloyd** [comment]
I think this has to do with people forcing it instead of waiting meaning that the air drains faster. I'll see about adding another canister though.

**Comment by liction15** [comment]
maybe though at roundstart it seems the canisters are almost empty or at least the sprite shows it at the red.

**Comment by Glloyd** [comment]
That's interesting. I'll look at the canisters themselves then.

**Comment by Glloyd** [comment]
That's interesting. I'll look at the canisters themselves then.

**Comment by liction15** [comment]
just checked it seems to start at 85kPa

**Comment by Glloyd** [comment]
will be fixed in #389

**Comment by Glloyd** [comment]
Should be fixed.
