### ISSUE TITLE
Janitor starts with engine access.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#358]
Unless this is intentional, the janitor starts with access to most of engineering, including directly into the SM chamber itself and the Singulo PA.

**Comment by Mark9013100** [comment]
On Bay, the Janitor has basic access to all departments.

**Comment by Glloyd** [comment]
That's definitely not intentional here.

On Wed, Mar 9, 2016 at 11:25 AM, Mark9013100 <notifications@github.com>
wrote:

> On Bay, the Janitor has basic access to all departments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/358#issuecomment-194375745>
> .
>



-- 
Graham Lloyd

**Comment by Mark9013100** [comment]
Well, atleast he can clean up the remains of foolish engineers!

**Comment by Glloyd** [comment]
Fixed
