### ISSUE TITLE
Spacebattle.dmm starts larger then it should be.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#374]
When the spacebattle away loads, it loads the map as 510x255 tiles, instead of 255x255, which is all that's used, I have no idea why.  This may be one of the reasons Spacebattle lags the server when it's loading.

**Comment by scrdest** [comment]
Weird af

**Comment by Glloyd** [comment]
what the fuck? Are you sure? It shouldnt be possible to have the map larger than 255x255. I'll look into it.

**Comment by Vakothu** [comment]
Yeah, whenever the spacebattle mission loads up, it's 510x255, Recently I noticed this every time the server chose spacebattle.

**Comment by Vakothu** [comment]
Don't know if you saw it, so I'm posting it as a new comment, I have the screenshot now, http://puu.sh/nKGMy/b14c7b0e03.png

**Comment by Glloyd** [comment]
wew

On Sat, Mar 19, 2016 at 11:23 PM, Michael <notifications@github.com> wrote:

> Don't know if you saw it, so I'm posting it as a new comment, I have the
> screenshot now, http://puu.sh/nKGMy/b14c7b0e03.png
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/374#issuecomment-198839215>
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Will be fixed in #389

**Comment by Glloyd** [comment]
Or not, this goes deep. After a 4~ hours of testing, I htink I figured something out. The turfs list is too fuckhuge that things don't work the way they should, and the 255x of spacebattle gets added onto the station 255x. NOW. I shrunk sb to 254, and instead of 510 it was 509. So, it's obvious that it's being added on. What's interesting is that it's being added on to the x and not the y. I noticed the same issue with the jungle stuff, exact same thing. I'm fucking around with stuff to see what I can do. Did this happen before the merge?

**Comment by Vakothu** [comment]
Not sure if it happened before the merge, I just recently noticed it myself.

**Comment by Glloyd** [comment]
Just tested, confirmed as happening before the update. This is something that I'll look at in the near future, but it's not a major priority at the moment. I have some ideas for how to fix this, but it's a pretty complex process.

**Comment by Glloyd** [comment]
I THINK I FIGURED IT OUT. It's an issue with the maploader, not the fuckhuge amount of turfs. I'm going to test it when I get home tonight, but I think I figured it out. The maploader improperly assumes that the map is a certain size, and bumps up the maxx of the world to compensate. If I'm right, it might just be a one line fix!

**Comment by Vakothu** [comment]
Further update on this, when SpaceBattle is loaded as the away mission, it looks like all z-levels go to 510x255.

**Comment by Glloyd** [comment]
Yeah, it changed the world maxx to 510. I've figured it out and I'm gonna put the I'd as well as some optimizations for the map loader in #389

**Comment by Glloyd** [comment]
Fixed it finally.
