### ISSUE TITLE
Anti-spam / Spam account measures

### ISSUE THREAD

**Issue by dore0062** [UristMcStation/UristMcStation#376]
A minor problem as of late, something needs to be implemented, unfortunately, it happens too much, and it's difficult banning them if they multikey:

**OKAY SOLUTION:**
`Normal anti-spam measures`
- Prevents users from typing sentences that are too long. 
- Prevents users from sending too many chat messages too fast, blocking them from sending anymore for a set period of time if they do. 
- Ban certain names / set of characters from being used, such as "penis" and so forth (and common variations.)

This prevents hit-and-run spam, and mostly deflects any ruining of immersion of the game due to bad names. The only repercussion to this is they might spend more effort griefing, such as trying to murder crew members (although a checkpoint esque system at spawn could prevent this.)

**BETTER SOLUTION:**
`Shadow mute`
- User can still speak, ooc and adminhelp, but it only appears to him. It will not tell the user they are shadow-muted. 

This way, they think they are spamming, but in reality nobody can hear them. Downsides are it can be abused by being used on regular players, but we aren't a big corporation, so we probably don't have much to worry about. It's also probably the most difficult solution. An important thing is, this will also create a database of compromised accounts, so if future griefers try to use these accounts, they will be already shadow-muted instead of banned, so they will have no idea which accounts are working, and which are not. They could try them all, but I doubt they care that much.

**AWFUL SOLUTION:**
`this shouldn't have even been suggested`
- Enable a whitelist

**Comment by scrdest** [comment]
At least for ahelp, I'm fairly sure it's supposed to have something like this, with the verb being unavailable for general ahelps (as opposed to responding to an admin), but seems to be implemented in a shitty way that can be circumvented with a hotkey.

**Comment by Glloyd** [comment]
I vote for instagibbing anyone who copypastas WGW into chat.

On Sat, Mar 19, 2016 at 4:47 PM, scrdest <notifications@github.com> wrote:

> At least for ahelp, I'm fairly sure it's supposed to have something like
> this, with the verb being unavailable for general ahelps (as opposed to
> responding to an admin), but seems to be implemented in a shitty way that
> can be circumvented with a hotkey.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/376#issuecomment-198783957>
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Semi fixed by #390, gonna leave this open though.

**Comment by scrdest** [comment]
Good, the system in 390 is very rough; I won't give a way to work around it here as a security measure (you never know), but it covers just the most basic of spammers - which, admittably, is the kind we've been having lately.

**Comment by Skeeve2** [comment]
Might be a good idea to ban TOR as well, nobody probably uses it.

**Comment by Skeeve2** [comment]
Anti-spam def. didn't stop the OOC spammers. We'll have to create a manual shadow-mute I think.

**Comment by scrdest** [comment]
It didn't take, for some reason. It's in the config, but the game didn't toggle it on.

**Comment by Glloyd** [comment]
that's because i forgot to let Vac know about it. He has to do changes to
config.txt manually.

On Mon, Apr 4, 2016 at 4:17 PM, scrdest <notifications@github.com> wrote:

> It didn't take, for some reason. It's in the config, but the game didn't
> toggle it on.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/376#issuecomment-205477130>
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Oh. No great loss, probably, since I manually edited the config controller in the round, and it didn't trigger either.

**Comment by Skeeve2** [comment]
Still an issue

**Comment by CPU-Blanc** [comment]
Old issue. Latest baymerge has bought a lot of anti-spam measures
