### ISSUE TITLE
Particle Accelerator Issues

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#379]
When the PA is on with power set to 2, the sprites of the left and right parts of the EM containment grid are swapped.  And when you hack the PA to power level 3, via wire cutting, it has no sprite and doesn't work at all, even when on, until you turn the power back to 2.

Also, the top SMES of the four SMES in engineering only has one coil, while the other three in that room have four.

**Comment by Glloyd** [comment]
I blame Bay. It's just an icon_state mismatch. And I'll fix that SMES.

**Comment by Glloyd** [comment]
SMES issue has been fixed for a bit. I'll fix the PA issues for the next update.

**Comment by scrdest** [comment]
PA issue fixed in the next Bay merge.

**Comment by Glloyd** [comment]
This has been fixed for a while
