### ISSUE TITLE
Holodeck is broken.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#382]
When you try to use the holodeck control computer, all it gives is a "Current Loaded Programs:
Warning: Unable to locate holodeck." message.

**Comment by Glloyd** [comment]
Bay changed the size of the holodeck and added more decks. i feel like that
has something to do with it

On Thu, Mar 24, 2016 at 11:53 PM, Michael <notifications@github.com> wrote:

> When you try to use the holodeck control computer, all it gives is a
> "Current Loaded Programs:
> Warning: Unable to locate holodeck." message.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/382>
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
I'll try to add this to #389 because it's a map thing AFAIK.
