### ISSUE TITLE
Burned off robotic limbs become organic stumps

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#384]
One of my robotic hands got burned off by a shocked airlock and I tried to fix the burn damage with wire but it did not work. On a hunch I used an ointment and it was successfully applied even through the entire arm was robotic.

**Comment by scrdest** [comment]
Might be fixed now.

**Comment by scrdest** [comment]
Pretty damn sure it's been fixed; it's a Bay bug one way or another anyway.
