### ISSUE TITLE
Resource Technician job severely buggy

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#404]
The RTs do not receive a jumpsuit or an ID (but they do get a PDA) and, in one case, failed to spawn at all.

**Comment by CoZarctan** [comment]
My observation has been that resource technicians consistently spawn on the title screen.

**Comment by Glloyd** [comment]
It's fixed, I'll get Vactor to update the server again soon. Until then,
just use one of the alt_titles for Resource Technician, they all work fine.

On Sun, Apr 3, 2016 at 2:21 PM, CoZarctan <notifications@github.com> wrote:

> My observation has been that resource technicians consistently spawn on
> the title screen.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/404#issuecomment-205024546>
>



-- 
Graham Lloyd
