### ISSUE TITLE
Naera Cubes do not make Naeras when they are expanded.

### ISSUE THREAD

**Issue by Weer6** [UristMcStation/UristMcStation#411]
Steps to reproduce: Get Naera cube, spray with water, watch as regular monkey appears.

**Comment by CoZarctan** [comment]
@Glloyd screwed this up when he fixed #344. Looking into it now.

**Comment by Glloyd** [comment]
not sure why I commented that line out actually. As long as you can still put monkeys into the monkey recycler it should be fine.

**Comment by CoZarctan** [comment]
Yeah, you can still recycle monkeys. Can't recycle Neara or Farwa or whatever to make monkeys, but that's intended.

**Comment by scrdest** [comment]
Will fix, still an issue?

**Comment by CPU-Blanc** [comment]
Old issue. Naera's are no longer part of the codebase. Guess that's one way to fix it?
