### ISSUE TITLE
SCOM mobs use laser beams instead of plasma beams

### ISSUE THREAD

**Issue by Addle** [UristMcStation/UristMcStation#420]
The plasma bolts lactera and such fire come out as lasers, not as green plasma.

**Comment by Glloyd** [comment]
i forgot to resprite the beams to the new system. oops.

**Comment by Addle** [comment]
420th issue 

ayy lmao

**Comment by Glloyd** [comment]
blayyze it

On Fri, Apr 8, 2016 at 7:52 PM, Addle <notifications@github.com> wrote:

> 420th issue
>
> ayy lmao
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/420#issuecomment-207650381>
>



-- 
Graham Lloyd

**Comment by Weer6** [comment]
rip

**Comment by Glloyd** [comment]
This is an easy fix, now that S-COM maps are fixed, I'll fix this as well.

**Comment by Glloyd** [comment]
Oh, this has been fixed for a while.
