### ISSUE TITLE
Antagonist bans ban the player from ERT, death commando and syndicate death commando. 

### ISSUE THREAD

**Issue by Addle** [UristMcStation/UristMcStation#422]
All bans are lifted if one of these jobs have the bans removed. ERT is not a real antagonist and the latter two are admin event roles.

**Comment by Skeeve2** [comment]
Seems intentional.

**Comment by scrdest** [comment]
The latter two are definitely antags, so antag bans apply as they should, admin event or not. ERT is more debatable, but probably similar reasoning - that, and the way antags are structured now.

**Comment by Glloyd** [comment]
i dunno how to tag this, but it's likely not something that is going to get fixed because it's semi intentional and erts are considered antags by the game.

**Comment by Glloyd** [comment]
I forgot we had that label. If antag roles are reworked again at some point, we can return to this issue, but as it stands right now it's not really something we can fix, and not necessarily something that needs to be fixed. If someone is banned from antag not by their own request, I don't see an issue with them being banned from dsquid and whatnot, seeing as those roles provide more opportunities to murderbone than most antags do. The only issue is people like Cheedows who have specifically asked to be antag banned, and that can be easily addressed by 'mins.

So, closing this for now.
