### ISSUE TITLE
Eaten Bread Tube has no sprite

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#424]
1. Eat bread tube
2. finish eating bread tube
3. Try to pick something else up with same hand
4. Get very confused
5. Click drop
6. Alt click floor where you dropped thing.
7. ???
8. 404 Sprite not found

**Comment by Glloyd** [comment]
should be fixed by #487 iirc

**Comment by scrdest** [comment]
Status?

**Comment by CPU-Blanc** [comment]
Old issue. This has since been fixed
