### ISSUE TITLE
No Power Net Sensor for engine outputs

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#428]
There is no way to measure the power output of both engines via console without rewiring it to an existing power sensor. The current sensor only measures the power input between the supermatter SMES and APC. The singularity input lacks a sensor completely.

**Comment by CoZarctan** [comment]
You can always use a multitool on the wire leading into the SMES. Because of the way the sensors function, I'm not sure there's a nontrivial way to just stick one in there and have it work.
