### ISSUE TITLE
Prison window shutters missing

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#429]
This button
![fuck](https://i.gyazo.com/8bfdf091f9d2da3f9195077d3e407e37.png)

Is supposed to activate non-existent shutters on this window
![fuckers](https://i.gyazo.com/9179f567e55e9564e9c2643b006df946.png)

Either the button needs to be removed, as it does nothing at the moment, or the shutters(Re-added?)

Original intention of the shutters was to prevent bad/shitty prisoners (read : clowns, mimes, etc.) from immediately trying to break out that window. It was meant to be opened as a "good behavior" kind of thing. I'm almost debating if that window should be removed altogether.

**Comment by Glloyd** [comment]
that's my bad, i swapped them with blast shutters because they weren't
conencted to anything i could find. i'll add regular shutters linked to
that button too.

On Sun, Apr 10, 2016 at 6:12 PM, Skeeve2 <notifications@github.com> wrote:

> This button
> [image: fuck]
> <https://camo.githubusercontent.com/53dfe8ecdd85ee497dc2b3828b6200db5c127617/68747470733a2f2f692e6779617a6f2e636f6d2f38626664663039316639643264613366393139353037376433653430376533372e706e67>
>
> Is supposed to activate non-existent shutters on this window
> [image: fuckers]
> <https://camo.githubusercontent.com/bb9d17c1aa5c727ee9738982d9f2b9f6eb3274cb/68747470733a2f2f692e6779617a6f2e636f6d2f39313739663536376535356539353634653963323634336230303664663934362e706e67>
>
> Either the button needs to be removed or the shutters(Re-added?)
>
> Original intention of the shutters was to prevent bad/shitty prisoners
> (read : clowns, mimes, etc.) from immediately trying to break out that
> window. It was meant to be opened as a "good behavior" kind of thing. I'm
> almost debating if that window should be removed altogether.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/429>
>



-- 
Graham Lloyd
