### ISSUE TITLE
[REQUEST] A break random event.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#432]
I talked to Glloyd about this, and he said it wouldn't be too hard, so I'll just post it here as a request in case he forgot.

Split into two separate issues on request.

**Comment by Glloyd** [comment]
it's on my list. i'd started work on it, it'll be in this weekend

On Sun, Apr 10, 2016 at 7:45 PM, Michael <notifications@github.com> wrote:

> I talked to Glloyd about this, and he said it wouldn't be too hard, so
> I'll just post it here as a request in case he forgot.
>
> Split into two separate issues on request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/432>
>



-- 
Graham Lloyd
