### ISSUE TITLE
Stunprods act like /tg/ stun batons, instantly knocking down anyone it hits instead of dealing halloss.

### ISSUE THREAD

**Issue by Addle** [UristMcStation/UristMcStation#433]
EDIT: It deals halloss. It instaknockdowns ON TOP OF dealing halloss. Two prods is enough to KO.

**Comment by liction15** [comment]
Now that you mention this this did happen the last time I used stunprods a month ago but never really noticed as I assumed it just does a shitload of halloss like stunbatons.

**Comment by Glloyd** [comment]
weird as fuck. i'll change them over for the next update

On Sun, Apr 10, 2016 at 11:10 PM, liction15 <notifications@github.com>
wrote:

> Now that you mention this this did happen the last time I used stunprods a
> month ago but never really noticed as I assumed it just does a shitload of
> halloss like stunbatons.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/433#issuecomment-208142773>
>



-- 
Graham Lloyd
