### ISSUE TITLE
[Request] Add station.dm rigs to station

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#435]
There are a lot of RIGs that we currently do not have, except for the CE and unathi NT RIG, despite it already being coded in. The Rigs are located at /code/modules/clothing/spacesuits/rig/suits/station.dm. Would be nice to have at least one of each added in to the map.

**Comment by Glloyd** [comment]
Some of the rigs have higher damage resistance than sec armour, so i'm going to pick and choose some good ones.
