### ISSUE TITLE
Actions that would otherwise be stopped by moving away do not

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#438]
Handcuffing, taking items all will still happen even if the person runs away and is nowhere near in range.

**Comment by scrdest** [comment]
BS12 issue. They messed with the handcuffing code, so much I know, and IIRC do_mob which is the main proc for that kind of thing as well.

**Comment by Glloyd** [comment]
telehandcuffing is pretty serious.

**Comment by Glloyd** [comment]
@scrdest this is fixed with #487 is it not?

**Comment by scrdest** [comment]
Fairly sure it is. The do_mob proc responsible was edited to add the timer bars, so presumably Bay would fix it a long time ago there if not before, and I did not get any reports of it in the tests.

**Comment by Glloyd** [comment]
It's not fixed yet, honk. Gotta wait for that to be merged.
