### ISSUE TITLE
Light doesnt work/is very weak on the research shuttle when docked planetside

### ISSUE THREAD

**Issue by cgale212** [UristMcStation/UristMcStation#440]
When the research shuttle is docked at the outpost, all light seems to either stop working, or be very weak. Had a flashlight in hand, and it only lite up a 3x3 tile area, vs the normal larger area of a flashlight. the lightbulb on it also produces no light when planetside.

**Comment by Glloyd** [comment]
Yeah, it's a weird issue with some of the shuttles. I'm trying to figure out what's causing it.
