### ISSUE TITLE
Add a "Toggle AOOC" and a "Toggle Ahelp" button

### ISSUE THREAD

**Issue by Stefender** [UristMcStation/UristMcStation#449]

**Comment by Glloyd** [comment]
I don't think a toggle ahelp button is a great idea because it allows admins to ignore ahelps for little benefit.

**Comment by scrdest** [comment]
It's for ahelp spam, I believe.

**Comment by CPU-Blanc** [comment]
Old issue. Toggle AOOC has since been added.
