### ISSUE TITLE
Main Hallway inadequately compartmentalized for ZAS atmo

### ISSUE THREAD

**Issue by Psyentific** [UristMcStation/UristMcStation#453]
Half the time when some jackass welderbombs Tool Storage, you can count on *gasp'ing as far away as Medbay as the entirety of the hallway's air supply escapes out that one space tile. Compartmentalizing the cavernous primary hallway into discrete, department-based, airlocked-off areas, ideally with their own room designation (ie APC, Air Alarm, Vent, Scrubber) ought to help with that problem.

I've created a mock-up laying out airlocks and hallways. Each department ought to have its own dedicated hall section and no hall section ought to have more than a screen and a half without some form of airlock or emergency door. Overall, a lot of the large hallways have been broken up into smaller ones, and the central public area has been chunked off into the main plaza and adjacent hallways. Major intersections have also been airlocked off into their own compartments. The overall effect is that the high-traffic areas of the station are much more granular, which will hopefully impede large-scale decompression.
![urist mcstation compartments](https://cloud.githubusercontent.com/assets/6664133/14842097/ff1be70c-0bf8-11e6-8677-29241feda131.png)

Black indicates airlocks, while orange indicates firelocks

**Comment by Glloyd** [comment]
Yeah, definitely need more doors, seeing as the map was originally made for FEA, then adapted for LINDA and only partially adapted for ZAS. The individual hallways do have their own APCs and whatnot too, they're just not sectioned off as much as they could be. I'll do that right now.
