### ISSUE TITLE
Northeast maint of Atmospherics provides no radstorm protection

### ISSUE THREAD

**Issue by andersonconagher** [UristMcStation/UristMcStation#454]
Yep.

**Comment by Glloyd** [comment]
It's because it's not a real maint and it's part atmospherics itself. I'll
reclassify it as the maint across the hall. I think it's the locker room
maint.

On Thu, Apr 28, 2016 at 6:40 PM, andersonconagher <notifications@github.com>
wrote:

> Yep.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/454>
>



-- 
Graham Lloyd
