### ISSUE TITLE
Traitor cham kit spawns with a .45 pistol and two lethal .45 magazines for 3tc

### ISSUE THREAD

**Issue by Addle** [UristMcStation/UristMcStation#464]
3tc for a lethal weapon that deals respectable damage, even if its only .45

Jesus christ please replace the ammo with the marshmellow rounds or raise the price.

**Comment by scrdest** [comment]
It used to deal 1 damage before, how it became lethal I don't even.

**Comment by Glloyd** [comment]
It isn't lethal, I just tested it out on the server. The magazine just says .45 but it still fires chameleon bullets.
