### ISSUE TITLE
[Request] Add monkey suit in maint

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#475]
cgale - Today at 12:08 AM
I would love for the monkey siut to be obtainable atleast in main somewhere

**Comment by Glloyd** [comment]
is there not a chance one of the costume landmarks can spawn it?

On Wed, Jun 1, 2016 at 3:48 AM, liction15 <notifications@github.com> wrote:

> cgale - Today at 12:08 AM
> I would love for the monkey siut to be obtainable atleast in main somewhere
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/475>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADyvWFxLQZNglc_MgM5U1tdOXU-VL7lYks5qHTlMgaJpZM4IrRjG>
> .
>



-- 
Graham Lloyd
