### ISSUE TITLE
The jungle is one ENTIRE place for the station blueprints

### ISSUE THREAD

**Issue by andersonconagher** [UristMcStation/UristMcStation#478]
So if I rename the jungle I cause massive lag because I'm renaming THE ENTIRE PLANET.

**Comment by Mapleguy555** [comment]
One APC can also power the entire jungle.

**Comment by Glloyd** [comment]
i've been meaning to make the planet function similar to space for the
purpose of blueprints. gonna actually do that now.

On Mon, Jun 6, 2016 at 6:56 PM, Mapleguy555 <notifications@github.com>
wrote:

> One APC can also power the entire jungle.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/478#issuecomment-224113940>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADyvWNUyEKFuI5Kk8z7Zvg22WloL2b6Oks5qJKW3gaJpZM4IvYkx>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
that mayyyyy fix it. but not gonna close it.

**Comment by Glloyd** [comment]
Yeah, this was fixed with that commit, forgot to close this.
