### ISSUE TITLE
Dark Spot: Research Station, Xenobotany Lab

### ISSUE THREAD

**Issue by Grant4455** [UristMcStation/UristMcStation#480]
Top left corner of the lab has a very dark spot. Makes it hard to work with anything in the tray, or use the machines. Stick a light tube in there instead of the bulb and yer golden mate. Oh. And a plant analyser. Move it from under the cables to the hydroponics box. It's fucking invisible where it is right now.

**Comment by Glloyd** [comment]
Will be fixed by #487
