### ISSUE TITLE
Bans have misleading information (and a typo)

### ISSUE THREAD

**Issue by Stefender** [UristMcStation/UristMcStation#485]
Still outdated and linking to Prevess instead of our new page.
Also typo "Permenant", likely from Bay.

Refer to this Picture:
![181d68ebb1644ef1a97fa2afde3c1480](https://cloud.githubusercontent.com/assets/13089876/16052829/4a670bae-3266-11e6-81dd-a6cfe58697e8.png)

**Comment by Glloyd** [comment]
This has been fixed on the main branch for some time. If it's still not working, it'll work after the next update because the config is going to get updated regardless.
