### ISSUE TITLE
Cyborg armor plating + welding tool bug

### ISSUE THREAD

**Issue by Gloribth** [UristMcStation/UristMcStation#491]
Repairing a dented cyborg (whose armor plating was damage) with a welding tool does not work. Clicking the cyborg 20 times with a fueled, active welding tool does nothing to repair the damage on the armor plating, but the welding tool's fuel units are used up from clicking on the cyborg.

Source: was cyborg, had 68% hull integrity. someone tried welder fixing me by clicking 20+ times but there were absolutely no repairs, only welding fuel units losses.

EDIT: Admin heal apparently works on all other stuff on cyborg except armor plating. Armor plating may be the bugged part here.

**Comment by CPU-Blanc** [comment]
Old issue. Has since been fixed.
