### ISSUE TITLE
Mimes can speak and their IDs don't open the mime/clown office. 

### ISSUE THREAD

**Issue by Glloyd** [UristMcStation/UristMcStation#501]
As in the title.

**Comment by scrdest** [comment]
I'm not sure about making them unable to speak. The IDs it an oversight, will have to check if it's the ID access that's wrong or the mapping that is, probably the latter.

**Comment by Glloyd** [comment]
Sorry, wasn't fully clear on that, I just copy and pasted what was sent to me. Mimes have lost their speech toggle along with their mimewall ability.

The ID thing applies to clowns too, and it's the weirdest fucking thing. It doesn't give either job their access, but it gives blue shields access, meaning it's not an issue with Urist jobs in general, just those two.
