### ISSUE TITLE
Patrolling Bots do not patrol Correctly

### ISSUE THREAD

**Issue by Stefender** [UristMcStation/UristMcStation#508]
#### Description of issue
Beepsky, Citizien Riot and any constructed CleanBots are supposed to patrol around the station in a circle pattern. They do not do that. Arrivals -> Escape -> Telecoms -> Cargo  (Repeat)

Beepsky will patrol from Escape to Telecoms.
He takes a fairly long ammount of time at Telecoms and then moves back to Escape.
_Ignoring Cargo and Arrivals._

**IF** citizien Riot is active at the SAME time, they will eventually Sinc up and move as one unit, Interestingly enough they do NOT move to telecoms anymore and default to moving between Escape and Arrivals. 
_Ignoring Telecoms and Cargo_

Cleanbots ignore the list completely, after trying for a while.
After they notice that patrolling is beneath them, they will instead default to the nearest spot they can clean. It takes them fairly long to calculate that, but it apparently works.

#### Difference between expected and actual behavior
Security
Expected: Circle
Actual: Line

Cleanbot
Expected: Circle
Actual: Anything but a Circle

#### Steps to reproduce 
Playing the game and paying attention to the bots

#### Specific information for locating

/mob/living/bot/cleanbot 
/mob/living/bot/secbot/beepsky 

#### Length of time in which bug has been known to occur

Since the last big update.

#### Server revision & Game ID

Server revision: master - 
d7d3bf31ca5c536ce8593b4c280c0bb252ea73b5
Game ID: bK1-c5LA

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Glloyd** [comment]
The navigation beacons must've gotten mixed up at some point. I'll look into it.

**Comment by Glloyd** [comment]
Similar to #359

It was fixed, and then it wasn't and then it was and now it isn't again. Grrr.

**Comment by Vakothu** [comment]
Not sure if it's a contributing factor, but the Cargo Beacon tries to send them to a SecHall2 beacon, which we don't have, we have a Sec Beacon (Near the doorways to Sec) and a SecHall beacon (Between IAA's office and Cryosleep.)

**Comment by Glloyd** [comment]
That's probably part of it. Right now I'm just redoing all of them. Going to make Beeps's whole route more comprehensive.

**Comment by Glloyd** [comment]
update: beeps goes to the janitors office first, then starts making a continuous loop. progress.
