### ISSUE TITLE
Spawned templates (jungle) don't have lighting.

### ISSUE THREAD

**Issue by Vakothu** [UristMcStation/UristMcStation#511]
Templates spawned roundstart in the jungle do not have lighting, unlike the rest of the jungle.

**Comment by Glloyd** [comment]
It's a known issue with templates, they don't work well with lighting. I'm trying to figure out a fix, have been for a while. It's a weird thorny issue that I just can't seem to find a fix for.

**Comment by Glloyd** [comment]
after a semi sleepless night spent tearing apart turf/template code to find the issue, i think it's an issue with the map loader itself. going to go back to sleep and tear that apart when i wake up.

**Comment by Glloyd** [comment]
HOLY SHIT, I FIXED IT!

All I had to do was make templates use ChangeTurf() instead of the system they used before.

**Comment by Glloyd** [comment]
This has been pissing me off ever since I added templates back in March. Holy shit, this is the most satisfying fix ever.
