### ISSUE TITLE
Unable to spawn as Botanist / other jobs after round start

### ISSUE THREAD

**Issue by Naverin** [UristMcStation/UristMcStation#524]
#### Description of issue
After round start.  Certain jobs are unavailable to spawn as.

Botanist
Virologist? 

any others ?  (attached screenshot)

I verifed under crew manafest that these jobs were not filled

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x
![capture](https://cloud.githubusercontent.com/assets/11949554/21375406/537805b6-c6fb-11e6-9370-6bfc93a246f8.JPG)
] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by scrdest** [comment]
Virologist is a Medical Doctor alt-title, and it's right there so it works. 

I don't recall ever having issues with spawning as Botanist late either, might be that there simply wasn't a free slot, but I'll look into it.

**Comment by scrdest** [comment]
Update: I checked when hosting, it seems like we forgot to add it to Glloydstation jobs.

**Comment by scrdest** [comment]
Fixed in https://github.com/UristMcStation/UristMcStation/commit/afd0cb01f633ec22cdffcf8496011d8fc99df1e9
