### ISSUE TITLE
Broken inhands and a few other errors.

### ISSUE THREAD

**Issue by Naxodile** [UristMcStation/UristMcStation#543]
The following items appear to be worn on your character while holding them in your hands.
/labcoat/cmo/alt
/armor/vest/capcarapace
/labcoat/robotics
/coat/jacket
/coat/jacket/leather
/urist/conductor
The security armored biosuit causes your gloves and shoes to disappear.
/bio_suit/asec
The necromancer's hood doesn't have a sprite for it's item.
/wizard/urist/necro

**Comment by Glloyd** [comment]
These are all urist icons that probably don't use the new urist icon macro

**Comment by scrdest** [comment]
Yep; I added them to all /urist/ clothes and all the ones I found in uristclothes.dm, probably also tg/nt ones, but... well, goes to show why code organization is important.

What do you mean with the necro hood? That it doesn't have an inhand, or the actual *sprite*?

**Comment by Naxodile** [comment]
The only time you see the necro hood sprite is on your character. Everywhere else it's invisible.

**Comment by Glloyd** [comment]
I'll fix these in #542, because I've already been fucking with all the clothing .dms and .dmis
