### ISSUE TITLE
Away template "Lar Maria" is outdated and cause server crashes 

### ISSUE THREAD

**Issue by martinlyra** [UristMcStation/UristMcStation#664]
#### Description of issue
The away site Lar Maria has been identified as one of the culprits of server crashes. It is simply outdated, trying to run a server with it guaranteed (with `template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED` in the `map_template` definition) crashes when building the Overmap.

#### Difference between expected and actual behavior
Expected: No crashes
Actual: Crashes at overmap-building stage.

#### Steps to reproduce 
Put `template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED` in `/datum/map_template/ruin/away_site/lar_maria` of `maps/away/lar_maria/lar_maria.dm`

Such as
```DM
/datum/map_template/ruin/away_site/lar_maria
	name = "Lar Maria"
	id = "awaysite_lar_maria"
	description = "An orbital virus research station."
	suffixes = list("lar_maria/lar_maria-1.dmm", "lar_maria/lar_maria-2.dmm")
	cost = 2

	template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED
```

#### Specific information for locating
See reproduction.

#### Length of time in which bug has been known to occur
Unknown

#### Client version, Server revision & Game ID
Tested and reproduced with 512.1463 and revision a4b192ada51a7046e3127cb892a899c54be6e038

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by martinlyra** [comment]
As I had noted in another development in the #bug_reports channel on Discord. Lar Maria has been isolated thoroughly and is not an culprit to crashes. 

But it still has an outdated type in its definition, thankfully it doesn't cause an issue on its own, it won't be spawned in the final product.

**Comment by scrdest** [comment]
Re: crashes, I've noticed there's a crap-ton of runtime errors popping up when I'm testing Noir on Nerva, and chances are at least _some_ of those aren't my fault :^)

It seems related to the callback system; I recall some of the runtimes were dealing with qdel()ing the smoke effects, but I only noticed this issue checking my work repos. Discord adress still the same?

**Comment by martinlyra** [comment]
[Welcome aboard!](https://discord.gg/4FB7CBK) @scrdest - For the future, I am not aware of any address to the Discord and we have an open invite policy, so anyone can generate a link.

**Comment by Glloyd** [comment]
@scrdest Discord address is still the same, yeah. You should still have your coder rank on there. @martinlyra Did we confirm that it wasn't related to Lar Maria but instead was related to exoplanets? Because if that's the case, I'll close this and make a separate issue, because I've fixed the outdated path on Lar Maria.

**Comment by martinlyra** [comment]
Sorry for the late response. For future reference, I am indeed Irra in Discord. And yes we did conclude that the issue was related to exoplanets and their ruins (particularly the marooned template). Closing this.
