### ISSUE TITLE
Unbuckling from chairs stops you from interacting with stuff.

### ISSUE THREAD

**Issue by ggermanicus** [UristMcStation/UristMcStation#763]
#### Description of issue
When you unbuckle (or are unbuckled) from a chair you can't click on stuff. Shoot guns, grab guns, hit people, press buttons, touch computers, and so on. For about 7-8 seconds. Examines and right-click actions still work. Seems to happen every single time.

#### Difference between expected and actual behavior
I should be able to unbuckle from chairs and still use things.

#### Steps to reproduce 
Buckle self in chair.
Unbuckle from chair.
Click on thing.

#### Length of time in which bug has been known to occur

Only really noticed it back in April, but it's probably gone on longer than that.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

I sure could find issues. From September 2018. That are still open. Suffer well friend.

**Comment by CPU-Blanc** [comment]
I know this is an old issue. I don't recall this being a thing in the current code, is it still an issue?

**Comment by ggermanicus** [comment]
Long ago fixed.
