### ISSUE TITLE
Multi-Z rendering do not account atom.layer settings

### ISSUE THREAD

**Issue by martinlyra** [UristMcStation/UristMcStation#899]
#### Description of issue
What it says in the title.

Open-space rendering vs actual content underneath
![image](https://user-images.githubusercontent.com/13331724/88255926-0d755c80-ccba-11ea-869e-3e696eef4dbd.png)
(From downstream with fixes, when floor decals were fixed. But object layers were not)

#### Difference between expected and actual behavior
Expected: Floor decals are shown as how they are in the current Z
Actual: Floor decals are shown above objects when seen from above.

#### Steps to reproduce 
Map open-space over floor tiles with floor decals and objects. Then watch the open-space rendering of these tiles from above.

#### Specific information for locating
`code/modules/multiz/turf.dm`

A fix is avaliable from downstream.

#### Length of time in which bug has been known to occur
Since forever. Baymerge-test version of the mentioned file doesn't show any changes at all.

#### Client version, Server revision & Game ID
N/A

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Old issue. This has since been fixed.
