### ISSUE TITLE
Improper boolean check cause north-facing stairs to disappear in multi-Z

### ISSUE THREAD

**Issue by martinlyra** [UristMcStation/UristMcStation#901]
#### Description of issue
In `code/module/multiz/turf.dm`, at line [115](https://github.com/UristMcStation/UristMcStation/blob/master/code/modules/multiz/turf.dm#L115)
`abs(O.pixel_y) >= 8 || abs(O.pixel_x) >= 8 && !istype(O, /obj/structure/stairs`

Instead of
`(abs(O.pixel_y) >= 8 || abs(O.pixel_x) >= 8) && !istype(O, /obj/structure/stairs`
or, rewriting the entire statement:
```DM
if (!istype(O, /obj/structure/stairs))
	if(abs(O.pixel_y) >= 8 || abs(O.pixel_x) >= 8)
		continue
```

The very first statement causes the north-facing stairs, which are shifted down with `pixel_y = -32` to disappear when seen from above with multi-Z.

#### Difference between expected and actual behavior
N/A

#### Steps to reproduce 
N/A

#### Specific information for locating
`code/module/multiz/turf.dm`

#### Length of time in which bug has been known to occur
Since forever

#### Client version, Server revision & Game ID
N/A

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Old issue. This has since been fixed
