### ISSUE TITLE
Traitor Weapon issues. (Silenced Holdout Pistol, Camera Bug Kit)

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#909]
#### Description of issue

- The Silenced Holdout Pistol's sprite fully disappears when out of ammunition, making it impossible to reload.
- The Camera Bug kit will constantly flicker between you, and the camera bug. (Unsure if this is intended, Bay?)

#### Difference between expected and actual behavior

- Silenced Pistol should have a seperate sprite in which the slide is back to signify it needs to be reloaded instead of disappearing.
- Camera Bug kit should keep you in the camera view until you cancel or move again.

#### Steps to reproduce 

- Buy a Silenced Holdout Pistol, run out of ammo. Gun will immediatley disappear.
- Use and set-up the bug kit and use the bug kit PDA, you will constantly flicker.

#### Specific information for locating
`UristMcStation\code\modules\projectiles\guns\projectile\pistol.dm`  Starting at line 186.
`/obj/item/weapon/storage/box/syndie_kit/spy` for the bugkit.

#### Length of time in which bug has been known to occur
Presumed to be Baymerge, due to the repathing of Bay Weapons from one of their refactors.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Laniakeaaaa** [comment]
Stechkin Pistol fixed in upcoming patch.
