### ISSUE TITLE
PDA Context Menu missing Pick Up verb.

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#910]
#### Description of issue

- PDA lacks the ability in the context menu to be picked up, yet other items do.

![image](https://user-images.githubusercontent.com/53942081/88426716-8e7f4180-cde9-11ea-9f46-121cf13a4cc2.png)

#### Difference between expected and actual behavior

- PDAs should be able to be grabbed in the context menu, as they previously were able to be.

#### Steps to reproduce 
- Drop your PDA on the floor, and attempt to pick it up using the right click menu, you will not be able to.

#### Length of time in which bug has been known to occur
Believed to be caused during the Baymerge. As you were previously able to do it before.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by CPU-Blanc** [comment]
Has been fixed as of the latest merge
