### ISSUE TITLE
Discarding cards makes them delete, instead of dropping them.

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#913]
#### Description of issue
When discarding a card from a hand, the mob will discard into the **`contents`** list, instead of onto the floor, or table nearby, effectively removing the card.

### This is fixed in:
https://github.com/Baystation12/Baystation12/pull/26465

#### Difference between expected and actual behavior
Card should be placed on the floor/table when discarded.

Actual Behaviour: Card disappears forever.

#### Steps to reproduce 
Discard a card from a hand of cards and it will disappear.

#### Specific information for locating
code/modules/games/cards.dm

#### Client version, Server revision & Game ID
Byond: 512.1488

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment]
Old issue. Fixed upstream
